### ISSUE TITLE
Error while loading database on OpenBSD

### ISSUE THREAD

**Issue by eyesackmeerkat** [GeyserMC/Floodgate#101]
I'm running papermc with geyser/floodgate on openbsd.  I get the following when the server starts:
```
[16:13:46 ERROR]: [floodgate-bukkit] Error while loading database
java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.JDBC.connect(JDBC.java:90) ~[patched_1.16.4.jar:git-Paper-393]
        at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:251) ~[java.sql:?]
        at org.geysermc.floodgate.link.SQLitePlayerLink.load(SQLitePlayerLink.java:25) ~[?:?]
        at org.geysermc.floodgate.PlayerLink.initialize(PlayerLink.java:47) ~[?:?]
        at org.geysermc.floodgate.BukkitPlugin.onLoad(BukkitPlugin.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.Exception: No native library found for os.name=OpenBSD, os.arch=x86_64, paths=[/usr/lib:/usr/local/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[patched_1.16.4.jar:git-Paper-393]
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[patched_1.16.4.jar:git-Paper-393]
        ... 15 more
```

**Comment by rtm516** [comment]
Can you try and install the sqlite-jdbc package for your os?

**Comment by eyesackmeerkat** [comment]
I added -classpath ".:sqlite-jdbc-VERSION.jar" to my java startup script and it did not work.
Still doesn't work when I put it in /usr/local/lib.

Is there some obvious way to install that I am missing?

Sorry I'm a noob :P

**Comment by rtm516** [comment]
Did you install the package using your package manager? And I don't use BSD so I would suggest just googling around to see if you can find a fix.

**Comment by eyesackmeerkat** [comment]
OpenBSD does not come with sqlite-jdbc library and it is not in ports. I downloaded sqlite-jdbc source, compiled, and put libsqlitejdbc.so in /usr/local/lib.

This fixed the error.
Thanks!

**Comment by Tim203** [comment]
Glad that the issue has been resolved.
