### ISSUE TITLE
Error when running /linkaccount: "Error while checking if the given player is linked. Please check the console for more info!"  linked-players.db SQLite database is empty.

### ISSUE THREAD

**Issue by openspork** [GeyserMC/Floodgate#106]
I get this error when trying to run `/linkaccount`: "Error while checking if the given player is linked. Please check the console for more info!"

I looked at the console and found errors, I will paste those at the end.

The errors in particular were regarding SQLite, so I figured I would look at linked-players.db manually.  A `SELECT * FROM LinkedPlayers` demonstrates that the database is in fact empty.

So, my rough conclusion of the issue is that when users join the SQLite operation is failing and therefor the linkage between players cannot be consulted.

I am running OpenJDK 11.0.9 and the most recent Paper, Floodgate end Geyser at the time of writing..

Errors from console:
```
[17:56:11 INFO]: [Geyser-Spigot] /192.168.166.223:64315 tried to connect!
[17:56:12 INFO]: [Geyser-Spigot] Player connected with username UserName
[17:56:14 INFO]: [Geyser-Spigot] Attempting to login using floodgate mode... authentication will be encrypted.
[17:56:14 INFO]: [Geyser-Spigot] Loaded Floodgate key!
[17:56:14 INFO]: [Geyser-Spigot] UserName (logged in as: UserName) has connected to remote java server on address 10.13.13.5
[17:56:14 WARN]: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: capacity < 0: (-100 < 0)
[17:56:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[17:56:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
[17:56:14 WARN]:        at org.geysermc.floodgate.FloodgatePlayer.fetchLinkedPlayer(FloodgatePlayer.java:97)
[17:56:14 WARN]:        at org.geysermc.floodgate.FloodgatePlayer.<init>(FloodgatePlayer.java:75)
[17:56:14 WARN]:        at org.geysermc.floodgate.HandshakeHandler.handle(HandshakeHandler.java:48)
[17:56:14 WARN]:        at org.geysermc.floodgate.PacketHandler.channelRead0(PacketHandler.java:65)
[17:56:14 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:56:14 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[17:56:14 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:56:14 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[17:56:14 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:56:14 WARN]:        at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:56:14 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:56:14 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:56:14 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:56:14 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:56:14 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:56:14 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[17:56:14 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[17:56:14 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[17:56:14 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[17:56:14 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[17:56:14 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:56:14 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:56:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:56:14 WARN]: Caused by: java.lang.IllegalArgumentException: capacity < 0: (-100 < 0)
[17:56:14 WARN]:        at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
[17:56:14 WARN]:        at java.base/java.nio.CharBuffer.allocate(CharBuffer.java:347)
[17:56:14 WARN]:        at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:792)
[17:56:14 WARN]:        at java.base/java.nio.charset.Charset.decode(Charset.java:814)
[17:56:14 WARN]:        at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[17:56:14 WARN]:        at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[17:56:14 WARN]:        at org.sqlite.core.DB.column_names(DB.java:733)
[17:56:14 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[17:56:14 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[17:56:14 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[17:56:14 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[17:56:14 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[17:56:14 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[17:56:14 WARN]:        at org.geysermc.floodgate.link.SQLitePlayerLink.lambda$getLinkedPlayer$0(SQLitePlayerLink.java:41)
[17:56:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[17:56:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[17:56:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[17:56:14 WARN]:        ... 1 more
[17:56:14 INFO]: [floodgate-bukkit] Added *UserName 00000000-0000-0000-0009-01fa97f7226c
[17:56:14 INFO]: UUID of player *UserName is 00000000-0000-0000-0009-01fa97f7226c
[17:56:14 INFO]: [Geyser-Spigot] Registering bedrock skin for *UserName (00000000-0000-0000-0009-01fa97f7226c)
[17:56:14 INFO]: [Geyser-Spigot] Unable to load bedrock skin for '*UserName' as they are likely using a customised skin
[17:56:14 INFO]: *UserName joined the game
[17:56:14 INFO]: *UserName[/192.168.166.223:35805] logged in with entity id 1516 at ([world]-5.984828, 63.0, 4.9181447)
```

**Comment by Camotoy** [comment]
Have you tried backing up the database and linking again?

**Comment by openspork** [comment]
@Camotoy Yes, I have deleted the database, observed a new blank database return on server restart, and reproduced the issue.

**Comment by Tim203** [comment]
Does this also happen in Floodgate 2.0?

**Comment by muzak23** [comment]
I can confirm this happens on floodgate 2.0, using the sqlite jar.
My specific error on 2.0: [https://mclo.gs/GyJQbNd](https://mclo.gs/GyJQbNd)

**Comment by Tim203** [comment]
Are there still people experiencing this problem?
