### ISSUE TITLE
"Failed to remove the injection!" on server stop

### ISSUE THREAD

**Issue by LemonHard** [GeyserMC/Floodgate#13]
Seems not to affect server/plugin behavior but that's here each time i stop server. fyi.

`[05:09:45] [Server thread/INFO]: [floodgate-bukkit] Disabling floodgate-bukkit v1.0-SNAPSHOT
[05:09:45] [Server thread/ERROR]: [floodgate-bukkit] Failed to remove the injection!
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_242]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_242]
        at org.geysermc.floodgate.injector.BukkitInjector.removeInjection(BukkitInjector.java:87) ~[floodgate-bukkit.jar:?]
        at org.geysermc.floodgate.BukkitPlugin.onDisable(BukkitPlugin.java:41) [floodgate-bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:430) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:396) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:699) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:689) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:864) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
`

**Comment by Heath123** [comment]
I get a lot this too

**Comment by Tim203** [comment]
Sure, will look at it
