### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by shelbykauth** [GeyserMC/Floodgate#141]
I'm using SpigotPaper (paper-1.16.5-629.jar), and the latest versions of floodgate-bukkit.jar and Geyser-Spigot.jar (https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/ and https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/)

I couldn't get any combination of ip or url, custom port, default port, default minecraft port (etc) to work.  Then I looked in the console logs.

Floodgate refuses to load, and when I try switching the auth-type to 'floodgate', it switches back because it can't find Floodgate.  I've looked inside the jar (changed filename to .zip and opened it normally), and I can't find plugin.yml, either.

The relevant logs are as follows:
```
25.04 21:10:49 [Server] ERROR Could not load 'plugins/floodgate-bukkit.jar' in folder 'plugins'
25.04 21:10:49 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
25.04 21:10:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
25.04 21:10:49 [Server] INFO Caused by: java.util.zip.ZipException: error in opening zip file
25.04 21:10:49 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_282]
25.04 21:10:49 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_282]
25.04 21:10:49 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_282]
25.04 21:10:49 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_282]
25.04 21:10:49 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_282]
25.04 21:10:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.5.jar:git-Paper-629]
25.04 21:10:49 [Server] INFO ... 6 more
```

**Comment by Camotoy** [comment]
Redownload Floodgate - generally that error means you either don't have a plugin jar (which you do), or your download is corrupt.

**Comment by shelbykauth** [comment]
But I've downloaded it two or three times and the same thing keeps happening.

**Comment by shelbykauth** [comment]
I guess I have to swallow my words... It did indeed work that time.
