### ISSUE TITLE
Errors when starting floodgate

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [GeyserMC/Floodgate#196]
Hello I have problems with floodgate, geyser connects me correctly but I have problems with floodgatea although I have their versions utliams stops working.

https://dump.geysermc.org/djGJbTtMvSgF9rSl67JIOawLXLZJT7di

**Comment by GeRmAnAnToNiO124** [comment]
THE ERROR is this in the console:
[02:13:46 ERROR]: Exception in thread "main" java.lang.NoClassDefFoundError: org/geysermc/floodgate/shaded/net/kyori/adventure/text/flattener/ComponentFlattener
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$BuilderImpl.<init>(LegacyComponentSerializerImpl.java:488)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer.builder(LegacyComponentSerializer.java:113)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.net.kyori.adventure.text.serializer.bungeecord.BungeeComponentSerializer.<clinit>(BungeeComponentSerializer.java:51)
[02:13:46 ERROR]:       at org.geysermc.floodgate.util.BungeeUserAudience$BungeeConsoleAudience.sendMessage(BungeeUserAudience.java:118)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.net.kyori.adventure.audience.Audience.sendMessage(Audience.java:207)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.net.kyori.adventure.audience.Audience.sendMessage(Audience.java:183)
[02:13:46 ERROR]:       at org.geysermc.floodgate.player.UserAudience.sendMessage(UserAudience.java:57)
[02:13:46 ERROR]:       at org.geysermc.floodgate.command.main.MainCommand.execute(MainCommand.java:75)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176)
[02:13:46 ERROR]:       at org.geysermc.floodgate.shaded.cloud.commandframework.bungee.BungeeCommand.execute(BungeeCommand.java:78)
[02:13:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
[02:13:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
[02:13:46 ERROR]:       at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
[02:13:46 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
[02:13:46 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
[02:13:46 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[02:13:46 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
[02:13:46 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[02:13:46 ERROR]: Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.shaded.net.kyori.adventure.text.flattener.ComponentFlattener
[02:13:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97)
[02:13:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[02:13:46 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:13:46 ERROR]:       ... 19 more

**Comment by GeRmAnAnToNiO124** [comment]
Specifications:
BungeeCord Waterfall

**Comment by GeRmAnAnToNiO124** [comment]
https://dump.geysermc.org/djGJbTtMvSgF9rSl67JIOawLXLZJT7di
https://mclo.gs/hQgYi9p

**Comment by Camotoy** [comment]
Please provide a complete log.

**Comment by GeRmAnAnToNiO124** [comment]
https://mclo.gs/No5zXde this is the latest log

**Comment by MrPranklez** [comment]
I seem to be running into the exact same issue, also using waterfall, not sure if that may at fault of this issue

**Comment by TAD3V** [comment]
I have this same issue and I'm not sure how to fix it. Did you make any progress?

**Comment by Tim203** [comment]
This should be fixed in Floodgate build 30
