### ISSUE TITLE
Bedrock players cannot see their inventory

### ISSUE THREAD

**Issue by voigtman** [GeyserMC/Floodgate#202]
`[23:46:56] [Geyser player thread-2-3/WARN] [Geyser-BungeeCord]: Could not translate packet ServerWindowItemsPacket
java.lang.ClassCastException: class com.github.steveice10.opennbt.tag.builtin.CompoundTag cannot be cast to class com.github.steveice10.opennbt.tag.builtin.ListTag (com.github.steveice10.opennbt.tag.builtin.CompoundTag and com.github.steveice10.opennbt.tag.builtin.ListTag are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @19f9d595)
	at org.geysermc.connector.network.translators.item.translators.nbt.EnchantmentTranslator.translateToBedrock(EnchantmentTranslator.java:47) ~[?:?]
	at org.geysermc.connector.network.translators.item.ItemTranslator.translateToBedrock(ItemTranslator.java:152) ~[?:?]
	at org.geysermc.connector.inventory.GeyserItemStack.getItemData(GeyserItemStack.java:95) ~[?:?]
	at org.geysermc.connector.inventory.Inventory.updateItemNetId(Inventory.java:128) ~[?:?]
	at org.geysermc.connector.inventory.Inventory.setItem(Inventory.java:111) ~[?:?]
	at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:50) ~[?:?]
	at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96) ~[?:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:46:56] [Geyser player thread-2-3/ERROR]: java.lang.ClassCastException: class com.github.steveice10.opennbt.tag.builtin.CompoundTag cannot be cast to class com.github.steveice10.opennbt.tag.builtin.ListTag (com.github.steveice10.opennbt.tag.builtin.CompoundTag and com.github.steveice10.opennbt.tag.builtin.ListTag are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @19f9d595)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.network.translators.item.translators.nbt.EnchantmentTranslator.translateToBedrock(EnchantmentTranslator.java:47)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.network.translators.item.ItemTranslator.translateToBedrock(ItemTranslator.java:152)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.inventory.GeyserItemStack.getItemData(GeyserItemStack.java:95)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.inventory.Inventory.updateItemNetId(Inventory.java:128)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.inventory.Inventory.setItem(Inventory.java:111)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:50)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:46:56] [Geyser player thread-2-3/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by Chew** [comment]
Doesn't seem to be related to Floodgate. Please reopen [here](https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&template=bug_report.yml)
