### ISSUE TITLE
Login Tag mismatch

### ISSUE THREAD

**Issue by ajh123** [GeyserMC/Floodgate#211]
So I have a simple bungeecord network like so
```
##############
# Internet   #
# --------   -------- Java player (works properly)
# All needed #
# ports are  -------- BE player joins gets error below
# open       #
###|##########
   |
   |
###|####################################
# waterfall       GeyserMC + Floodgate #
#  (proxy)>Plugins>(1.4.3) +   (2.0)   #
# 1.17-450          have same key.pem  #
####|###################################
    |
    |
    +---- paper-1.17.1-320  Floodgate 2.0  (lobby) have same key.pem
    |
    +---- paper-1.17.1-320  Floodgate 2.0  (other_world) have same key.pem
```

[Proxy side configs](https://pastebin.com/ZkCsGG2X)

[Paper sever configs](https://pastebin.com/bXEaB4WR)

But on the paper sever I get this error when I try to join as a Bedrock player
```
[12:28:17 WARN]: javax.crypto.AEADBadTagException: Tag mismatch!
[12:28:17 WARN]: 	at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:792)
[12:28:17 WARN]: 	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1122)
[12:28:17 WARN]: 	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1059)
[12:28:17 WARN]: 	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:855)
[12:28:17 WARN]: 	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:456)
[12:28:17 WARN]: 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
[12:28:17 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.crypto.AesCipher.decrypt(AesCipher.java:123)
[12:28:17 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.crypto.FloodgateCipher.decryptToString(FloodgateCipher.java:103)
[12:28:17 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.player.FloodgateHandshakeHandler.lambda$handle$0(FloodgateHandshakeHandler.java:106)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[12:28:17 WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[12:28:17 INFO]: [floodgate] An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.

```

**Comment by ajh123** [comment]
Still get the error :(

**Comment by Jens-Co** [comment]
Can you send a dump for us ? (Command : /geyser dump).

**Comment by ajh123** [comment]
Just so you know, my server is a network using waterfall, which has both GeyserMC and floodgate and the backend server are paper with just Floodgate

**Comment by ajh123** [comment]
Works now! Thank you!

**Comment by Jens-Co** [comment]
Did you disable the option on proxy as wel? Or only on your backend servers?
