### ISSUE TITLE
LinkageError when attempting to use Forms in Spigot

### ISSUE THREAD

**Issue by funniray** [GeyserMC/Floodgate#212]
Both Floodgate and Geyser include Cumulus in their Jars and Floodgate has an older(?) version of Cumulus. I believe this is an issue with Cumulus being shaded into the Floodgate jar mistakenly, as in all cases, Geyser (and Cumulus) should be present when Floodgate is loaded.

Here's the error that Spigot gives me when I attempt to open a form. Do note, this only happens on newer versions of Spigot. On older versions of Spigot, I was able to open forms fine.
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'void org.geysermc.connector.network.session.GeyserSession.sendForm(org.geysermc.cumulus.util.FormBuilder)' the class loader org.bukkit.plugin.java.PluginClassLoader @339f9461 of the current class, com/funniray/geyserutils/GeyserUtilsCommand, and the class loader org.bukkit.plugin.java.PluginClassLoader @61fd0ead for the method's defining class, org/geysermc/connector/network/session/GeyserSession, have different Class objects for the type org/geysermc/cumulus/util/FormBuilder used in the signature (com.funniray.geyserutils.GeyserUtilsCommand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @339f9461, parent loader 'app'; org.geysermc.connector.network.session.GeyserSession is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @61fd0ead, parent loader 'app')
at com.funniray.geyserutils.GeyserUtilsCommand.onCommand(GeyserUtilsCommand.java:27) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
```

Here's the code I run

```Java
session.sendForm(SimpleForm.builder()
        .title("Select Server")
        .button("Survival")
        .button("Creative")
        .responseHandler((form,responseData)->{
            SimpleFormResponse response = form.parseResponse(responseData);
            if (!response.isCorrect()) {
                return;
            }

            switch (response.getClickedButtonId()) {
                case 0:
                    Utils.transfer(session,"172.200.0.1",19133);
                    break;
                case 1:
                    Utils.transfer(session,"172.200.0.1",19134);
                    break;
            }
        })
);
```

**Comment by Camotoy** [comment]
Also, we just added API in Floodgate to transfer a player! https://github.com/GeyserMC/Floodgate/blob/master/api/src/main/java/org/geysermc/floodgate/api/FloodgateApi.java#L98

**Comment by funniray** [comment]
I'm not home right now, but I only depend on Spigot and Geyser-Connector -- both with the provided scope. The issue I have is with sending the form packet, as Floodgate's version of Cumulus seems to be different from Geyser's when you view the jar content for org.geysermc.cumulus in both the floodgate and cumulus jar -- causing the LinkageError.

**Comment by Tim203** [comment]
This issue at its core is the same issue as #178 and because of that I'm closing this issue in favor of #178.
