### ISSUE TITLE
Broken forms

### ISSUE THREAD

**Issue by samuelh2005** [GeyserMC/Floodgate#215]
So when my player joins in bungee cord I want to open a "form"

and my error is
```
Error dispatching event PostLoginEvent(player=.Samuel_Hulme) to listener net.ddns.minersonline.Events@b32e983
java.lang.LinkageError: loader constraint violation: loader net.md_5.bungee.api.plugin.PluginClassloader @765df79d wants to load interface org.geysermc.cumulus.util.FormBuilder. A different interface with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @53692008. (org.geysermc.cumulus.util.FormBuilder is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @53692008, parent loader 'app')
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at org.geysermc.floodgate.api.player.FloodgatePlayer.sendForm(FloodgatePlayer.java:119) ~[?:?]
	at net.ddns.minersonline.Events.postLoginEvent(Events.java:27) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:551) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-450.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[19:59:44] [Netty Worker IO Thread #5/WARN]: Event PermissionCheckEvent(sender=.Samuel_Hulme, permission=viaversion.update, hasPermission=false) took 306ms to process!
```

and this is [my code](https://github.com/ajh123-development/BungeeExtras/blob/main/src/main/java/net/ddns/minersonline/Events.java#L27)
and as you can see in my error I am using ```Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:f9d6629:450``` which is [PaperMC](https://papermc.io)'s fork of bungeecord

**Comment by ajh123** [comment]
Is there any other events that I can listen to?

**Comment by Camotoy** [comment]
Without using Geyser standalone, we are not aware of a workaround for this yet.
