### ISSUE TITLE
PaperSpigot and TacoSpigot (1.8.8) not supported

### ISSUE THREAD

**Issue by Boryte** [GeyserMC/Floodgate#219]
[20:29:59] [ERROR]: null initializing floodgate v2.0-SNAPSHOT (Is it up to date?)
java.lang.AbstractMethodError: null
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[?:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[?:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[?:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[?:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:96) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:73) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:62) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onLoad(SpigotPlugin.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(SourceFile:349) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:293) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:705) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by Boryte** [comment]
Bump

**Comment by Camotoy** [comment]
Did you test with no other plugins on Paper?

**Comment by Camotoy** [comment]
Can you try updating to the latest Floodgate version?

**Comment by Boryte** [comment]
> Can you try updating to the latest Floodgate version?

It's working perfectly now :D
Thanks
