### ISSUE TITLE
Floodgate no longer functions after the latest Velocity commit.

### ISSUE THREAD

**Issue by RealTriassic** [GeyserMC/Floodgate#222]
All builds after [this commit](https://github.com/VelocityPowered/Velocity/commit/cb8781b3c937cdc81e571edf6ee5e26e7b67675c) do not work with Floodgate, but to observe the issue you must use [this build](https://ci.velocitypowered.com/job/velocity-3.0.0/90/), due to shading issues preventing Velocity from functioning normally. 

When trying to join a Velocity server (running build [#90](https://ci.velocitypowered.com/job/velocity-3.0.0/90/) of Velocity) running Floodgate, you simply receive this error:

```
[06:54:01 ERROR] [floodgate]: Failed get the FloodgatePlayer from the player's channel
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
        at org.geysermc.floodgate.util.ReflectionUtils.getValue(ReflectionUtils.java:203) ~[?:?]
        at org.geysermc.floodgate.util.ReflectionUtils.getCastedValue(ReflectionUtils.java:233) ~[?:?]
        at org.geysermc.floodgate.listener.VelocityListener.onPreLogin(VelocityListener.java:93) ~[?:?]
        at org.geysermc.floodgate.listener.Lmbda$22.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.0-SNAPSHOT (git-7c858424-b90)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.0-SNAPSHOT (git-7c858424-b90)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.0-SNAPSHOT (git-7c858424-b90)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[06:54:01 INFO]: [initial connection] /IP has disconnected: Failed to get the FloodgatePlayer from the players's Channel
[06:54:05 ERROR]: java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.InitialInboundConnection.connection to com.velocitypowered.proxy.connection.client.LoginInboundConnection
[06:54:05 ERROR]:       at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[06:54:05 ERROR]:       at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[06:54:05 ERROR]:       at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[06:54:05 ERROR]:       at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
[06:54:05 ERROR]:       at java.base/java.lang.reflect.Field.get(Field.java:425)
[06:54:05 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.getValue(ReflectionUtils.java:203)
[06:54:05 ERROR]:       at org.geysermc.floodgate.listener.VelocityListener.onPreLogin(VelocityListener.java:92)
[06:54:05 ERROR]:       at org.geysermc.floodgate.listener.Lmbda$22.execute(Unknown Source)
[06:54:05 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[06:54:05 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[06:54:05 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[06:54:05 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:54:05 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:54:05 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Tim203** [comment]
Should be fixed in build 46
