### ISSUE TITLE
Floodgate fails to enable on Spigot+ 1.18

### ISSUE THREAD

**Issue by Chew** [GeyserMC/Floodgate#229]
Upon attempting to load floodgate on a dev build of (specifically, Paper) 1.18-pre5 causes errors. This is seemingly due to NMS changes on Spigot's end. 

As these are dev builds, there's no real priority for at least a week, but the issue should still be documented anyway.

The entire stack trace is below:

```
[02:06:29] [Server thread/INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[02:06:29] [Server thread/ERROR]: Error occurred while enabling floodgate v2.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:156) ~[?:?]
at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:59) ~[?:?]
at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:127) ~[?:?]
at org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48) ~[?:?]
at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:62) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:493) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1081) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[Paper-Server-reobf.jar:git-Paper-"8050360"]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Is whitelisted cannot be null
at org.geysermc.floodgate.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[?:?]
at org.geysermc.floodgate.util.ClassNames.checkNotNull(ClassNames.java:231) ~[?:?]
at org.geysermc.floodgate.util.ClassNames.(ClassNames.java:121) ~[?:?]
... 16 more
[02:06:29] [Server thread/INFO]: [floodgate] Disabling floodgate v2.0-SNAPSHOT
```

Geyser Dump, if needed: https://dump.geysermc.org/N9ujtk26ST7GTjFSyU6Ch4Pq2ThD1Xe9

**Comment by Sebastianjn007** [comment]
in mine this error appears when a bedrock player tries to connect
![Screenshot_20211201-061459](https://user-images.githubusercontent.com/79463461/144266201-327aeb67-aa2d-44d6-a23b-7734bdcb0c0f.png)

**Comment by Chew** [comment]
That issue is unrelated and I believe is due to corrupted keys, delete them and restart.

**Comment by Sebastianjn007** [comment]
I can't solve it, delete the folder and it still gives the same problem and when a bedrock enters this appears
![Screenshot_20211201-062516](https://user-images.githubusercontent.com/79463461/144283887-0bc7f59b-c11b-4f09-81d9-9602d2c7aeea.png)
Sorry, I don't know much in the old versions I just put the port on the geyse and the froadgate and it worked now on the 1.18 tou with this problem!

**Comment by Chew** [comment]
Please continue this on [Discord](https://discord.gg/geysermc)

**Comment by Chew** [comment]
Fixed in https://github.com/GeyserMC/Floodgate/commit/315efb9e50b50810fddf739c923dd2f6753f4d26
