### ISSUE TITLE
Language files missing

### ISSUE THREAD

**Issue by ThexXTURBOXx** [GeyserMC/Floodgate#234]
Encountered the following error when starting either current snapshots from `master` or `dev/2.1.1` branch:
```
[16:05:15] [Server thread/INFO]: [floodgate] Loading floodgate v2.1.1-SNAPSHOT
[16:05:17] [Server thread/WARN]: [floodgate] Missing locale file: en_US
[16:05:17] [Server thread/ERROR]: [floodgate] Failed to load the fallback language. This will likely cause errors!
[16:05:17] [Server thread/WARN]: [floodgate] en_US is not a supported Floodgate language.
[16:05:17] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] Cannot invoke "java.util.Properties.getProperty(String)" because "properties" is null initializing floodgate v2.1.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "properties" is null
	at org.geysermc.floodgate.util.LanguageManager.getString(LanguageManager.java:188) ~[?:?]
	at org.geysermc.floodgate.util.LanguageManager.getLogString(LanguageManager.java:158) ~[?:?]
	at org.geysermc.floodgate.logger.JavaUtilFloodgateLogger.translatedInfo(JavaUtilFloodgateLogger.java:64) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onLoad(SpigotPlugin.java:57) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

This can be fixed by manually inserting the languages repo in the jar file.
As you can see, the jars compiled by Jenkins don't contain these files, which generates the above error.

**Comment by Camotoy** [comment]
The master branch does have these files; please ensure you're using the latest one. The `dev/2.1.1` branch is not yet ready for use (it's a code restructure anyway).
