### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by hoehoetvhss** [GeyserMC/Floodgate#236]
**Version:** Floodgate 2.1.1 Dev

`
[01:34:02 ERROR]: Could not pass event PlayerLoginEvent to floodgate v2.1.1-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "properties" is null
        at org.geysermc.floodgate.util.LanguageManager.getString(LanguageManager.java:188) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.util.LanguageManager.getLogString(LanguageManager.java:158) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.logger.JavaUtilFloodgateLogger.translatedInfo(JavaUtilFloodgateLogger.java:64) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.listener.SpigotListener.onPlayerLogin(SpigotListener.java:59) ~[FloodGate.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:767) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:176) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:87) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:517) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

`
[01:35:09 WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by org.geysermc.floodgate.addon.AddonManagerAddon$$Lambda$7862/0x00000008020c1860.operationComplete()
java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "properties" is null
        at org.geysermc.floodgate.util.LanguageManager.getString(LanguageManager.java:188) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.util.LanguageManager.getLogString(LanguageManager.java:158) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.logger.JavaUtilFloodgateLogger.translatedInfo(JavaUtilFloodgateLogger.java:64) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.addon.data.SpigotDataAddon.onChannelClosed(SpigotDataAddon.java:70) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.inject.CommonPlatformInjector.channelClosedCall(CommonPlatformInjector.java:88) ~[FloodGate.jar:?]
        at org.geysermc.floodgate.addon.AddonManagerAddon.lambda$onInject$0(AddonManagerAddon.java:39) ~[FloodGate.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1182) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:773) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.local.LocalChannel.tryClose(LocalChannel.java:278) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.local.LocalChannel.access$300(LocalChannel.java:50) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.local.LocalChannel$4.run(LocalChannel.java:248) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by Camotoy** [comment]
Please use the master builds on version 2.1.0. Thanks!
