### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by weihao** [GeyserMC/Floodgate#237]
```
smp_1             | [08:23:05 INFO]: .user issued server command: /sethome
smp_1             | [08:23:05 WARN]: [AdvancedTeleport] Plugin AdvancedTeleport v5.5.6 generated an exception while executing task 37680
smp_1             | java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.api.player.FloodgatePlayer.getCorrectUniqueId()" because the return value of "org.geysermc.floodgate.api.FloodgateApi.getPlayer(java.util.UUID)" is null
smp_1             |     at io.github.niestrat99.advancedteleport.api.ATPlayer.<init>(ATPlayer.java:55) ~[AdvancedTeleport-Bukkit-5.5.6.jar:?]     
smp_1             |     at io.github.niestrat99.advancedteleport.api.ATPlayer.<init>(ATPlayer.java:46) ~[AdvancedTeleport-Bukkit-5.5.6.jar:?]     
smp_1             |     at io.github.niestrat99.advancedteleport.api.ATPlayer.getPlayer(ATPlayer.java:305) ~[AdvancedTeleport-Bukkit-5.5.6.jar:?] 
smp_1             |     at io.github.niestrat99.advancedteleport.commands.home.SetHomeCommand.onCommand(SetHomeCommand.java:27) ~[AdvancedTeleport-Bukkit-5.5.6.jar:?]
smp_1             |     at io.github.niestrat99.advancedteleport.managers.CommandManager.lambda$register$1(CommandManager.java:137) ~[AdvancedTeleport-Bukkit-5.5.6.jar:?]
smp_1             |     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-68]
smp_1             |     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-68]  
smp_1             |     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-68]
smp_1             |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
smp_1             |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
smp_1             |     at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This is spamming my console. Any reason why the API failed?

**Comment by Jens-Co** [comment]
Can you upload a code snippet ? Without much detail we cannot help you. 
thanks.

**Comment by weihao** [comment]
what code snippet? i am not the developer but there it is
https://github.com/Niestrat99/AT-Rewritten/blob/f7c220e4b2bbe423d8a65fcc7e3720b932dc7c4c/AdvancedTeleport-Bukkit/src/main/java/io/github/niestrat99/advancedteleport/api/ATPlayer.java#L59

**Comment by Jens-Co** [comment]
Can you do a sout before you cast uuid into api.isFloodgateId(uuid). Let me know what it returns. Not sure why you are getting null on uuid

**Comment by Tim203** [comment]
Make sure that you're not including the Floodgate api classes in your jar

**Comment by Chew** [comment]
As this is an issue with the plugin (and it's being tracked here: https://github.com/Niestrat99/AT-Rewritten/issues/58) I'm going to close this in favor of that. Regardless, thank you for the report!
