### ISSUE TITLE
Velocity Floodgate not tracking bedrock players

### ISSUE THREAD

**Issue by weihao** [GeyserMC/Floodgate#249]
```
[08:35:57] [Server thread/INFO]: [AdvancedTeleport] Is the player online?: true
[08:35:57] [Server thread/INFO]: [AdvancedTeleport] Floodgate player checked, UUID being checked: 00000000-0000-0000-0009-01f0c67e24e5, name: .xiaonai6318
[08:35:57] [Server thread/INFO]: [AdvancedTeleport] Player is being tracked by floodgate?: false
[08:35:57] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to AdvancedTeleport v5.5.7+DEV_${env.BUILD_NUMBER}
java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.api.player.FloodgatePlayer.getCorrectUniqueId()" because the return value of "org.geysermc.floodgate.api.FloodgateApi.getPlayer(java.util.UUID)" is null
	at io.github.niestrat99.advancedteleport.api.ATPlayer.<init>(ATPlayer.java:61) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at io.github.niestrat99.advancedteleport.api.ATPlayer.<init>(ATPlayer.java:46) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at io.github.niestrat99.advancedteleport.api.ATPlayer.getPlayer(ATPlayer.java:312) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at io.github.niestrat99.advancedteleport.managers.TeleportTrackingManager.onDeath(TeleportTrackingManager.java:86) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:896) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:862) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:923) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1027) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:1887) ~[?:?]
	at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1709) ~[?:?]
	at net.minecraft.world.level.block.Block.fallOn(Block.java:458) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1512) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:367) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1456) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1512) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Floodgate is installed on both velocity and spigot
_Originally posted by @weihao in https://github.com/Niestrat99/AT-Rewritten/issues/58#issuecomment-998881860_

**Comment by Camotoy** [comment]
Do you have `send-floodgate-data` enabled on the Velocity Floodgate?

**Comment by weihao** [comment]
> Do you have `send-floodgate-data` enabled on the Velocity Floodgate?

yes, it is enabled on the velocity plugin

**Comment by Thatsmusic99** [comment]
Coming from the mentioned issue as I'm the developer of the plugin throwing the error in the first place and had some time to look into this.

Changing `send-floodgate-data` to true does the trick *if* Geyser and Floodgate on both Velocity and Paper are configured correctly. I will modify my plugins as necessary to respond to this as I know the actual problem now. @weihao - with this in mind, definitely make sure the setup follows [this page](https://github.com/GeyserMC/Floodgate/wiki/Setup-and-Usage).

Feel free to contact either Geyser's team or myself over Discord if you do need any help regarding this.

**Comment by Tim203** [comment]
With the developer of the plugin confirming this, I'll close the issue.
Like the developer of the plugin said, make sure to follow the setup completely. There are some additional steps you have to follow when you want to access the Floodgate API on your backend servers.

If you need further assistance after following the setup, feel free to ask for it in our Discord.

**Comment by weihao** [comment]
@Tim203 

https://github.com/GeyserMC/Floodgate/wiki/Setup-and-Usage#installing-floodgate-also-on-spigot-servers-behind-bungeecord-or-velocity

this setup guide is very ambiguous for velocity users.

do i need to `Set bungeecord to true in your spigot.yml` for velocity?

besides this step, i had the same setup and was still getting the NPE error

**Comment by Konicai** [comment]
Please contact us on Discord for setup details like this, it'll be easier to help you there

For the record though, setup Velocity with modern forwarding if using Paper, or legacy BungeeCord forwarding if using Spigot. Information on how to do either is on velocitypowered.com
