### ISSUE TITLE
papi error

### ISSUE THREAD

**Issue by Shizuri23** [GeyserMC/Floodgate#250]
[PlaceholderAPI] failed to load class files of expansions 
>java.util.concurrent.CompletionException: java.lang.IllegalAccessError: class org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry cannot access its superinterface org.yaml.snakeyaml.parser.Production (org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry is in unnamed module of loader java.net.URLClassLoader @15f32127; org.yaml.snakeyaml.parser.Production is in unnamed module of loader java.net.URLClassLoader @5c29bfd) 
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] 
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] 
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] 
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] 
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] 
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] 
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] 
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] 
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] 
>Caused by: java.lang.IllegalAccessError: class org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry cannot access its superinterface org.yaml.snakeyaml.parser.Production (org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry is in unnamed module of loader java.net.URLClassLoader @15f32127; org.yaml.snakeyaml.parser.Production is in unnamed module of loader java.net.URLClassLoader @5c29bfd) 
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] 
at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] 
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?] 
at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?] 
at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?] 
at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?] 
at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?] 
at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 
at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[PlaceholderAPI-2.11.0.jar:?] 
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:388) ~[PlaceholderAPI-2.11.0.jar:?] 
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] 
... 6 more

**Comment by Konicai** [comment]
Does this stop occurring when you use Floodgate? 

Are you using https://github.com/rtm516/FloodgatePlaceholders ? If so, this isn't the place.

**Comment by Camotoy** [comment]
Yeah, this doesn't look like an us issue whatsoever, so I'm closing. If you think otherwise, please let us know!
