### ISSUE TITLE
Unable to find listening channel, players cannot join when floodgate is enabled

### ISSUE THREAD

**Issue by sashakoshka** [GeyserMC/Floodgate#258]
I am using geyser and floodgate (latest stable builds of both as of Sunday Jan 09 3:30 AM) as plugins on a spigot server. All ports are at their default. Whenever I reload the server, regardless if floodgate is enabled or not, a Java error appears once it starts setting up and it prints a stack trace. Below is a full output:

```
[03:33:39] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.0-SNAPSHOT
[03:33:40] [Server thread/INFO]: [Geyser-Spigot] Auto-loaded Floodgate key
[03:33:40] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[03:33:40] [Server thread/INFO]: [Geyser-Spigot] 
[03:33:40] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser version 2.0.0-SNAPSHOT (git-master-3251d90)
[03:33:40] [Server thread/INFO]: [Geyser-Spigot] 
[03:33:40] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[03:33:42] [Server thread/INFO]: [Geyser-Spigot] Loaded Floodgate key!
[03:33:42] [Server thread/INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[03:33:42] [Server thread/INFO]: [Geyser-Spigot] Done (2.541s)! Run /geyser help for help!
[03:33:42] [Server thread/WARN]: java.lang.RuntimeException: Unable to find listening channel!
[03:33:42] [Server thread/WARN]:        at org.geysermc.geyser.platform.spigot.GeyserSpigotInjector.initializeLocalChannel0(GeyserSpigotInjector.java:107)
[03:33:42] [Server thread/WARN]:        at org.geysermc.geyser.network.netty.GeyserInjector.initializeLocalChannel(GeyserInjector.java:64)
[03:33:42] [Server thread/WARN]:        at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:190)
[03:33:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:33:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[03:33:42] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:33:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526)
[03:33:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440)
[03:33:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:941)
[03:33:42] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:749)
[03:33:42] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[03:33:42] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[03:33:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[03:33:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:806)
[03:33:42] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:453)
[03:33:42] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429)
[03:33:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206)
[03:33:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034)
[03:33:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[03:33:42] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:33:42] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[03:33:42] [Server thread/INFO]: CONSOLE: Reload complete.
```

At one point, when I reloaded the server with floodgate enabled and Geyser using a different port than 19132, it started cleanly. I am unable to reproduce this.

When joining with a bedrock client, there is a prompt to download resource packs that are present on the server if they have not already been downloaded. Immediately after, the connection fails due to `io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer` and this stack trace is printed:

```
[03:36:54] [Netty Epoll Server IO #3/WARN]: java.lang.IllegalStateException: zip file closed
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.geysermc.floodgate.player.FloodgateHandshakeHandler.handle(FloodgateHandshakeHandler.java:118)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.geysermc.floodgate.addon.data.CommonDataHandler.handle(CommonDataHandler.java:93)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:111)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:36:54] [Netty Epoll Server IO #3/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)
```

I have noticed that when floodgate is disabled, bedrock clients can still connect, and the above error does not appear (even though the first one still does). This leads me to believe it is produced by floodgate.

I can provide both configuration files if need be, however I changed almost nothing. I am using no other plugins on the server.

I am running a 1.18 spigot server under openjdk 17 on Alpine Linux x86_64 musl.

**Comment by Camotoy** [comment]
We are aware of this issue: https://github.com/GeyserMC/Geyser/issues/2665. However, in general, it's not good practice to reload: https://madelinemiller.dev/blog/problem-with-reload/. This issue will be fixed eventually, since people reload anyway, but it's low priority. Thanks anyway for the issue.

**Comment by sashakoshka** [comment]
> We are aware of this issue: [GeyserMC/Geyser#2665](https://github.com/GeyserMC/Geyser/issues/2665). However, in general, it's not good practice to reload: https://madelinemiller.dev/blog/problem-with-reload/. This issue will be fixed eventually, since people reload anyway, but it's low priority. Thanks anyway for the issue.

Fully restarting spigot solved the issue, thanks!
