### ISSUE TITLE
carpetbots dont spawn with geyser/floodgate 

### ISSUE THREAD

**Issue by KarmaMarazu** [GeyserMC/Floodgate#262]
when i use the carpet mod and do /player alex spawn     it says in chat an unexpected error occurred trying to execute that command

if i turn in the carpet supersecretsettings i get this in console:
[20:33:28] [Server thread/INFO]: Alex[local] logged in with entity id 1269 at (-336.4833064362423, 121.0, -3511.941056074608)
[20:33:28] [Server thread/ERROR]: Command exception: /player Alex spawn
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
        at net.minecraft.class_3244.handler$zzh000$adventure$initTracking(class_3244.java:2162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.<init>(class_3244.java:202) ~[server-intermediary.jar:?]
        at carpet.patches.NetHandlerPlayServerFake.<init>(NetHandlerPlayServerFake.java:15) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
        at net.minecraft.class_3324.redirect$zdn000$replaceNetworkHandler(class_3324.java:2977) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:169) ~[server-intermediary.jar:?]
        at carpet.patches.EntityPlayerMPFake.createFake(EntityPlayerMPFake.java:65) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
        at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:316) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:262) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_14370(class_3244.java:1229) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_31286(class_3244.java:1213) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12048(class_3244.java:1196) ~[server-intermediary.jar:?]
        at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zcg000$modifiedRunLoop(MinecraftServer.java:3365) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

https://github.com/GeyserMC/Floodgate-Fabric/commit/84ddb0e59e45e0c449d07844513bbeeb4367a307 i have found this but i am still getting the problem (on the latest fabric floodgate and geyser) even though it should be fixed with that (i think)
if this can be fixed that would be amazing

**Comment by Camotoy** [comment]
This is an issue on Carpet's side: https://github.com/GeyserMC/Floodgate-Fabric/issues/37 and https://github.com/gnembon/fabric-carpet/pull/1235
