### ISSUE TITLE
Players can't connect

### ISSUE THREAD

**Issue by Thereaperpeper** [GeyserMC/Floodgate#268]
Hello, whenever bedrock players connect, they get timed out, with this message in the console:

[19:36:10 WARN]: java.lang.reflect.InvocationTargetException
[19:36:10 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:36:10 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:36:10 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:36:10 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:36:10 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:169)
[19:36:10 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:118)
[19:36:10 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:36:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:36:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:36:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:36:10 WARN]:        at ProtocolLib (6).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[19:36:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
[19:36:10 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[19:36:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[19:36:10 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[19:36:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[19:36:10 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:36:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:36:10 WARN]: Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[19:36:10 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[19:36:10 WARN]:        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
[19:36:10 WARN]:        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38)
[19:36:10 WARN]:        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
[19:36:10 WARN]:        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31)
[19:36:10 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191)
[19:36:10 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184)
[19:36:10 WARN]:        at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:398)
[19:36:10 WARN]:        ... 29 more

i have installed the latest versions of geyser, geyser-spigot, and floodgate-spigot.

**Comment by Camotoy** [comment]
Please install the latest Floodgate version; you are not updated. Also, you don't need to install Geyser and Geyser-Spigot into your plugins folder.
