### ISSUE TITLE
Bedrock Clients can not connect

### ISSUE THREAD

**Issue by sphings79** [GeyserMC/Floodgate#269]
```
[15:52:20 INFO]: [Geyser-Spigot] /46.83.190.185:55712 tried to connect!
[15:52:20 INFO]: [Geyser-Spigot] Player connected with username ZuluBueffel4602
[15:52:20 INFO]: [Geyser-Spigot] ZuluBueffel4602 (logged in as: ZuluBueffel4602) has connected to the Java server
[15:52:20 WARN]: java.lang.reflect.InvocationTargetException
[15:52:20 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:20 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:52:20 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:20 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:52:20 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:169)
[15:52:20 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:118)
[15:52:20 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[15:52:20 WARN]: 	at ClientDetector.jar//de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:39)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[15:52:20 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
[15:52:20 WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[15:52:20 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[15:52:20 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:52:20 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:52:20 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:52:20 WARN]: Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[15:52:20 WARN]: 	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[15:52:20 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
[15:52:20 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
[15:52:20 WARN]: 	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191)
[15:52:20 WARN]: 	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184)
[15:52:20 WARN]: 	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:398)
[15:52:20 WARN]: 	... 33 more
[15:52:20 INFO]: [floodgate] Floodgate player logged in as *ZuluBueffel4602 disconnected
[15:52:20 INFO]: [Geyser-Spigot] ZuluBueffel4602 has disconnected from the Java server because of Connection closed.
[15:52:20 INFO]: com.mojang.authlib.GameProfile@3e87ca16[id=00000000-0000-0000-0009-01f6eae7f8d0,name=*ZuluBueffel4602,properties={},legacy=false] (/46.83.190.185:0) lost connection: Disconnected
[15:52:20 INFO]: [Geyser-Spigot] Bedrock user with ip: /46.83.190.185 has disconnected for reason CLOSED_BY_REMOTE_PEER
```

version
[15:54:04 INFO]: Checking version, please wait...
[15:54:05 INFO]: This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are running the latest version
Previous version: git-Paper-186 (MC: 1.18.1)
version floodgate
[15:54:08 INFO]: floodgate version 2.1.0-SNAPSHOT
[15:54:08 INFO]: Allows Bedrock players to join Java edition servers while keeping the server in online mode
[15:54:08 INFO]: Website: https://github.com/GeyserMC/Floodgate/spigot
[15:54:08 INFO]: Author: GeyserMC
version geyser
[15:54:38 INFO]: Geyser-Spigot version 2.0.0-SNAPSHOT
[15:54:38 INFO]: Website: https://github.com/GeyserMC/Geyser/blob/master/pom.xml
[15:54:38 INFO]: Author: GeyserMC

**Comment by sphings79** [comment]
https://dump.geysermc.org/8ci4XxIO2ldNmkReWIA8WEoqfNzZb5N5

**Comment by sphings79** [comment]
Will try but worked like charme with alwaysonline since some days ...

**Comment by sphings79** [comment]
Will work. Now there is a new message in the log:

`[16:51:36 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.mojang.com/users/profiles/minecraft/*ZuluBueffel4602
[16:51:36 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
[16:51:36 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[16:51:36 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[16:51:36 WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[16:51:36 WARN]: 	at ProtocolFirewall-1.0.16.jar//me.galaxyeater.protocolfirewall.f.a.readJsonFromUrl(JsonReader.java:13)
[16:51:36 WARN]: 	at ProtocolFirewall-1.0.16.jar//me.galaxyeater.protocolfirewall.f.f.getUuidFromMojang(Utils.java:96)
[16:51:36 WARN]: 	at ProtocolFirewall-1.0.16.jar//me.galaxyeater.protocolfirewall.d.d.j.a.a(UUIDSpoofListener.java:38)
[16:51:36 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:51:36 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:51:36 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:51:36 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:51:36 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:51:36 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Camotoy** [comment]
That is another plugin issue. 
AlwaysOnline needs to fix an issue on their end where they don't call a Paper event. The reason it breaks now is not our fault; Mojang changed an API response on their end.

**Comment by sphings79** [comment]
Thx
