### ISSUE TITLE
Tried to log in as a Java Edition player! Is Floodgate set up correctly?

### ISSUE THREAD

**Issue by AlexXanderGrib** [GeyserMC/Floodgate#270]
# Setup

## Velocity 3.1.2-SNAPSHOT (git-596d4758-b111)
Plugins: discordlink, **floodgate**, **geyser**, lightmotd, limboapi, limbofilter, luckperms, skinsrestorer

## Paper git-Purpur-1551 (MC: 1.18.1)
Plugins (47): AttributeHider, BlueMap, Chunky, Citizens, CMI, CMILib, CoreProtect, CustomCrates, CustomHeads*, DeluxeMenus, Denizen, Essentials, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExecutableBlocks, ExecutableItems, FastAsyncWorldEdit (WorldEdit), **floodgate**, GSit, LightAPI, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, PancakeLibCore, PlaceholderAPI, Plan, PlayerParticles, Playtime, ProtocolLib, QAWorldGuard, QualityArmory, QualityArmoryVehicles2, SCore, Shopkeepers, SkinsRestorer, spark, TabList, Themis, Vault, Votifier, WorldGuard, YamipaPlugin

## Configs
[geyser.yml.txt](https://github.com/GeyserMC/Floodgate/files/8041649/geyser.yml.txt)
[floodgate-velocity.yml.txt](https://github.com/GeyserMC/Floodgate/files/8041650/floodgate-velocity.yml.txt)
[floodgate-paper.yml.txt](https://github.com/GeyserMC/Floodgate/files/8041651/floodgate-paper.yml.txt)

# Error

Appears on velocity. Purpur sends no logs. The error does not depend on whether the player is linked or not

```log
[17:01:56] [Network Listener - #0/INFO]: /<ip>:54012 попытался подключиться!
[17:01:56] [Network Listener - #2/INFO]: Подключен игрок с именем пользователя AlexXanderGrib
[17:01:56] [defaultEventLoopGroup-6-1/INFO]: AlexXanderGrib (вошёл как: AlexXanderGrib) подключился к серверу Java
[17:01:57] [pool-8-thread-1/INFO]: Floodgate player who is logged in as AlexXanderGrib 72cc8d3f-9559-4b1e-bec4-6f2d7669a78f joined
[17:01:57] [Netty epoll Worker #1/INFO]: Игрок AlexXanderGrib вошедший через Floodgate отключился
[17:01:57] [Netty epoll Worker #1/INFO]: [initial connection] /<ip>:0 has disconnected
[17:01:57] [defaultEventLoopGroup-6-1/INFO]: AlexXanderGrib отключился от сервера Java по причине Tried to log in as a Java Edition player! Is Floodgate set up correctly?
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: com.github.steveice10.mc.protocol.data.UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:156)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:377)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:28)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:01:57] [defaultEventLoopGroup-6-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:01:57] [Network Listener - #0/INFO]: Bedrock пользователь с IP: /<ip> отключился по причине CLOSED_BY_REMOTE_PEER
```

**Comment by AlexXanderGrib** [comment]
I saw the word "encryption" in the error message, and yes, floodgate keys are identical

```
root@794605-alexxgrib:~/velocity# sha256sum plugins/floodgate/key.pem 
c0aa9feed8c8714c3422180968ab6dd7805c8c884a00a49c8c60819e2096e856  plugins/floodgate/key.pem
```

```
root@793293-alexxgrib:~/minecraft# sha256sum plugins/floodgate/key.pem 
c0aa9feed8c8714c3422180968ab6dd7805c8c884a00a49c8c60819e2096e856  plugins/floodgate/key.pem
```

**Comment by AlexXanderGrib** [comment]
Referring to this [reddit post](https://www.reddit.com/r/GeyserMC/comments/r9cuz7/problem_with_bedrock_connection/), I tried to install `ViaVersion` and `ViaBackwards` on the proxy, but after seeing this error I removed them, but it is not gone

**Comment by Camotoy** [comment]
Please try removing all other plugins other than Geyser and Floodgate from Velocity.

**Comment by AlexXanderGrib** [comment]
I removed ALL plugins and reinstalled them and this helped

**Comment by AlexXanderGrib** [comment]
After installing all plugins again I understood that cause of this error was `limboapi` or `limbofilter` plugins
