### ISSUE TITLE
Unsafe concurrency in `VelocityCommandUtil`

### ISSUE THREAD

**Issue by Quantum64** [GeyserMC/Floodgate#278]
`getAudience` mutates `AUDIENCE_CACHE` map, but this method can be called from multiple threads. Observed in high-load environments.

```
2022-03-07 10:00:54.333  INFO 187416 --- [y NIO Worker #7] 120725p : [server connection] bot_9b2c3def -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.384  INFO 187416 --- [y NIO Worker #8] 120776p : [server connection] bot_743a05e4 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.384  INFO 187416 --- [y NIO Worker #9] 120776p : [server connection] bot_7af27a8b -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.384  INFO 187416 --- [ NIO Worker #13] 120776p : [server connection] bot_ae6613a6 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.384  INFO 187416 --- [ NIO Worker #11] 120776p : [server connection] bot_137c71bd -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.384  INFO 187416 --- [ NIO Worker #10] 120776p : [server connection] bot_94c9e4f7 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.385  INFO 187416 --- [ NIO Worker #18] 120777p : [server connection] bot_c86d4e49 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.440  INFO 187416 --- [ NIO Worker #12] 120832p : [server connection] bot_08828f18 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.440  INFO 187416 --- [ NIO Worker #16] 120832p : [server connection] bot_ff9f181f -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.440  INFO 187416 --- [ NIO Worker #20] 120832p : [server connection] bot_2be2269c -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.440  INFO 187416 --- [ NIO Worker #19] 120832p : [server connection] bot_7d2f21a2 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.441  INFO 187416 --- [ NIO Worker #15] 120833p : [server connection] bot_3e59429c -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.443  INFO 187416 --- [ NIO Worker #21] 120835p : [server connection] bot_fa9db1e5 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.443  INFO 187416 --- [ NIO Worker #26] 120835p : [server connection] bot_7c1100e2 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.443  INFO 187416 --- [ NIO Worker #14] 120835p : [server connection] bot_ab0c8abe -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.488  INFO 187416 --- [ NIO Worker #24] 120880p : [server connection] bot_8d36cab6 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.488  INFO 187416 --- [ NIO Worker #23] 120880p : [server connection] bot_e23794e1 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.536  INFO 187416 --- [ NIO Worker #27] 120928p : [server connection] bot_f94cbce3 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.536  INFO 187416 --- [ NIO Worker #17] 120928p : [server connection] bot_f1129996 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.583  INFO 187416 --- [ NIO Worker #22] 120975p : [server connection] bot_8d02447d -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.583  INFO 187416 --- [ NIO Worker #28] 120975p : [server connection] bot_ace817cb -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.583  INFO 187416 --- [ NIO Worker #31] 120975p : [server connection] bot_fafb280e -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.583  INFO 187416 --- [ NIO Worker #25] 120975p : [server connection] bot_288318f4 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.646  INFO 187416 --- [ NIO Worker #33] 121038p : [server connection] bot_29ede0dd -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.646  INFO 187416 --- [ NIO Worker #32] 121038p : [server connection] bot_4d587c0e -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.646  INFO 187416 --- [ NIO Worker #30] 121038p : [server connection] bot_1dcb2743 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.646  INFO 187416 --- [ NIO Worker #29] 121038p : [server connection] bot_e4dcbfc0 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.693  INFO 187416 --- [ NIO Worker #37] 121085p : [server connection] bot_14b7e078 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.693  INFO 187416 --- [ NIO Worker #34] 121085p : [server connection] bot_f3ec8a24 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.693  INFO 187416 --- [ NIO Worker #38] 121085p : [server connection] bot_b17bb8b3 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.693  INFO 187416 --- [ NIO Worker #36] 121085p : [server connection] bot_75645c90 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.693  INFO 187416 --- [ NIO Worker #35] 121085p : [server connection] bot_44730f0e -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.787  INFO 187416 --- [ NIO Worker #39] 121179p : [server connection] bot_791205ec -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.882  INFO 187416 --- [ NIO Worker #41] 121274p : [server connection] bot_95f58803 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.882  INFO 187416 --- [ NIO Worker #40] 121274p : [server connection] bot_6eaab89c -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.882  INFO 187416 --- [ NIO Worker #42] 121274p : [server connection] bot_1138d30b -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.882  INFO 187416 --- [ NIO Worker #43] 121274p : [server connection] bot_d595d1ae -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.882  INFO 187416 --- [ NIO Worker #44] 121274p : [server connection] bot_93afceab -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.976  INFO 187416 --- [ NIO Worker #46] 121368p : [server connection] bot_bdb54b94 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.976  INFO 187416 --- [y NIO Worker #0] 121368p : [server connection] bot_86cc3078 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:54.976  INFO 187416 --- [ NIO Worker #47] 121368p : [server connection] bot_d1ac6f4d -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:55.072  INFO 187416 --- [y NIO Worker #1] 121464p : [server connection] bot_6b243722 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:55.119  INFO 187416 --- [ NIO Worker #45] 121511p : [server connection] bot_69b771ee -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:55.119  INFO 187416 --- [y NIO Worker #2] 121511p : [server connection] bot_c39f52c5 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:55.360  INFO 187416 --- [y NIO Worker #6] 121752p : [server connection] bot_51acca55 -> b3735f7e-2821-4f66-b26b-d40382d47dc6 has connected
2022-03-07 10:00:55.404 ERROR 187416 --- [ NIO Worker #10] 121796p : [server connection] bot_94c9e4f7 -> b3735f7e-2821-4f66-b26b-d40382d47dc6: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@34f66cae

java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
        at org.geysermc.floodgate.util.VelocityCommandUtil.getAudience(VelocityCommandUtil.java:78) ~[floodgate-63:?]
        at org.geysermc.floodgate.shaded.cloud.commandframework.velocity.VelocityPluginRegistrationHandler.lambda$registerCommand$2(VelocityPluginRegistrationHandler.java:71) ~[floodgate-63:?]
        at org.geysermc.floodgate.shaded.cloud.commandframework.brigadier.CloudBrigadierManager.lambda$createLiteralCommandNode$22(CloudBrigadierManager.java:445) ~[floodgate-63:?]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:80) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at com.velocitypowered.proxy.command.CommandGraphInjector.inject(CommandGraphInjector.java:76) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handle(BackendPlaySessionHandler.java:258) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.handle(AvailableCommands.java:189) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.1:3.1.2-SNAPSHOT (git-9c44aff8-b117)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.73.Final:4.1.73.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.73.Final:4.1.73.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.73.Final:4.1.73.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.73.Final:4.1.73.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.73.Final:4.1.73.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Tim203** [comment]
This code has been removed in the Floodgate 2.1.1 dev builds. Feel free to download those builds [here](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.1.1/)

**Comment by Quantum64** [comment]
Sounds good. Thanks.
