### ISSUE TITLE
when player /shop

### ISSUE THREAD

**Issue by A212H212** [GeyserMC/Floodgate#282]
[12:16:33] [Server thread/ERROR]: Could not pass event PreFillProfileEvent to floodgate v2.1.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null
	at org.geysermc.floodgate.api.SimpleFloodgateApi.isFloodgateId(SimpleFloodgateApi.java:101) ~[?:?]
	at org.geysermc.floodgate.api.SimpleFloodgateApi.getPlayer(SimpleFloodgateApi.java:81) ~[?:?]
	at org.geysermc.floodgate.api.SimpleFloodgateApi.isFloodgatePlayer(SimpleFloodgateApi.java:73) ~[?:?]
	at org.geysermc.floodgate.listener.PaperProfileListener.onFill(PaperProfileListener.java:44) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:26) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:90) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:57) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$3.call(TileEntitySkull.java:231) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.TileEntitySkull$3.call(TileEntitySkull.java:228) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.TileEntitySkull.b(TileEntitySkull.java:247) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:104) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:535) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at me.gypopo.economyshopgui.objects.NavBar.addMainMenuNavBar(NavBar.java:462) ~[?:?]
	at me.gypopo.economyshopgui.objects.MainMenu.open(MainMenu.java:36) ~[?:?]
	at me.gypopo.economyshopgui.commands.Shop.execute(Shop.java:50) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2267) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1330) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1323) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1299) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1143) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"5e8ac76"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
	
	
This is my error

**Comment by Gaming32** [comment]
Whatever shop plugin this is appears to be passing `null` to the Floodgate API. This doesn't appear to be Floodgate's fault.

**Comment by HookWoods** [comment]
Try to update to latest floodgate version
This commit should fix this stacktrace https://github.com/GeyserMC/Floodgate/commit/da663b606a38f06774702e34c0d60661568e0f63
