### ISSUE TITLE
Player global linking using velocity unable to connect from bedrock

### ISSUE THREAD

**Issue by andreaslutsch** [GeyserMC/Floodgate#299]
I'm running geyser and floodgate as plugins for [velocity](https://velocitypowered.com).
I run minecraft 1.18.2 using the newest stable geyser and floodgate and velocity snapshot for 1.18.2 support.

When having player linking turned on, connecting with java is possible, but connecting through a globally linked account, joining fails.
Turning player linking off allows to join as a user with prefix.

```
[12:50:16 INFO] [geyser]: Player connected with username AndreasusX
[12:50:16 INFO] [geyser]: AndreasusX (logged in as: AndreasusX) has connected to the Java server
[12:50:16 INFO] [floodgate]: Floodgate player who is logged in as AndreasusX 73ef5f67-673c-[4](https://mclo.gs/KFgigkz#L4)0af-9070-97ae7ce647[5](https://mclo.gs/KFgigkz#L5)3 joined
[12:50:1[6](https://mclo.gs/KFgigkz#L6) INFO]: [connected player] AndreasusX (/**.**.**.**:0) has connected
[12:50:16 INFO]: [server connection] AndreasusX -> nethros has connected
[12:50:16 INFO]: [server connection] AndreasusX -> nethros has disconnected
[12:50:16 ERROR]: [connected player] AndreasusX (/**.**.**.**:0): unable to connect to server nethros com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
[12:50:16 INFO]: [connected player] AndreasusX (/**.**.**.**:0) has disconnected: Unable to connect you to nethros. Please try again later.
[12:50:16 INFO] [geyser]: AndreasusX has disconnected from the Java server because of Unable to connect you to nethros. Please try again later.
[12:50:16 INFO] [floodgate]: Floodgate player logged in as AndreasusX disconnected
```

This may be a similar to issue, as #281 as both use proxies.

**Comment by Camotoy** [comment]
Please also provide logs of the backend server as you're joining.

**Comment by andreaslutsch** [comment]
I accidentally closed the issue.

I am able to get an error now in the velocity console:

```
[13:03:51 ERROR]: Exception during connect; status = null
java.util.concurrent.CompletionException: com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity-3.1.2-SNAPSHOT-138.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[velocity-3.1.2-SNAPSHOT-138.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity-3.1.2-SNAPSHOT-138.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.2-SNAPSHOT-138.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-138.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-138.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
[13:03:51 ERROR]: [connected player] AndreasusX (/46.5.19.238:0): unable to connect to server limbo
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
```

The error appears and I am unable to connect only when `enable-global-linking` is set to `true`.

**Comment by Konicai** [comment]
Could you share a `/geyser dump` please?

**Comment by andreaslutsch** [comment]
Since opening the issue, I have set up the server with pterodactyl and I haven't had this issue anymore.
