### ISSUE TITLE
floodgate not loading on bungeecord

### ISSUE THREAD

**Issue by scattyypie** [GeyserMC/Floodgate#307]
WARNING] Error loading plugin floodgate
org.geysermc.floodgate.shaded.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingMethod]: IncompleteAnnotationException: Named missing element value
  at FloodgatePlatform.init(FloodgatePlatform.java:88)
  while locating FloodgatePlatform

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_METHOD

1 error

======================
Full classname legend:
======================
FloodgatePlatform:             "org.geysermc.floodgate.FloodgatePlatform"
IncompleteAnnotationException: "java.lang.annotation.IncompleteAnnotationException"
Named:                         "javax.inject.Named"
========================
End of classname legend:
========================

    at org.geysermc.floodgate.shaded.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
    at org.geysermc.floodgate.BungeePlugin.onLoad(BungeePlugin.java:55)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:224)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:41)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:12)
Caused by: java.lang.annotation.IncompleteAnnotationException: javax.inject.Named missing element value
    at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:86)
    at jdk.proxy2/jdk.proxy2.$Proxy19.value(Unknown Source)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.Annotations.canonicalizeIfNamed(Annotations.java:385)
    at org.geysermc.floodgate.shaded.com.google.inject.Key.strategyFor(Key.java:356)
    at org.geysermc.floodgate.shaded.com.google.inject.Key.get(Key.java:263)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.Annotations.getKey(Annotations.java:349)
    at org.geysermc.floodgate.shaded.com.google.inject.spi.InjectionPoint.<init>(InjectionPoint.java:113)
    at org.geysermc.floodgate.shaded.com.google.inject.spi.InjectionPoint$InjectableField.toInjectionPoint(InjectionPoint.java:503)
    at org.geysermc.floodgate.shaded.com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:789)
    at org.geysermc.floodgate.shaded.com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:423)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:173)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:671)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:628)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:614)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:943)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:843)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:301)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:224)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1092)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1121)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1086)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
    at org.geysermc.floodgate.FloodgatePlatform.init(FloodgatePlatform.java:104)
    at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5644740.GUICE$TRAMPOLINE(<generated>)
    at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5644740.apply(<generated>)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
    at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
    ... 7 more

**Comment by Camotoy** [comment]
Are you using a custom BungeeCord fork? I'm pretty sure I've only seen this issue there.

**Comment by scattyypie** [comment]
yes am using aegis escanor

**Comment by scattyypie** [comment]
but am pretty sure floodgate works on aegis escanor

**Comment by Jens-Co** [comment]
Someone had the exact same issue few days ago. Floodgate isn't working on aegis.

**Comment by scattyypie** [comment]
it worked before but it doesnt work now

**Comment by scattyypie** [comment]
i just wanted floodgate for replacing spaces in bedrock usernames

**Comment by Tim203** [comment]
Please contact the developers of aegis if you want to see this fixed.
BungeeCord and Waterfall don't have this issue.
