### ISSUE TITLE
Floodgate Throwing Error With Latest Version of BungeeCord

### ISSUE THREAD

**Issue by iLuckyx** [GeyserMC/Floodgate#312]
Bungeecord Version: #1642 (https://ci.md-5.net/job/BungeeCord/)
GeyserMC Version: Geyser-BungeeCord.jar #1108

Error: https://pastebin.com/MjRG97Pq

`01:58:38 [INFO] [floodgate] Floodgate player logged in as -iiLucky8534 joined (UUID: 00000000-0000-0000-0009-0000060cf001)
01:58:38 [WARNING] Error dispatching event PostLoginEvent(player=-iiLucky8534) to listener org.geysermc.floodgate.listener.BungeeListener@552ffa44
java.lang.NoSuchMethodError: 'void net.md_5.bungee.connection.LoginResult.<init>(java.lang.String, java.lang.String, net.md_5.bungee.connection.LoginResult$Property[])'
    at org.geysermc.floodgate.pluginmessage.BungeeSkinApplier.applySkin(BungeeSkinApplier.java:73)
    at org.geysermc.floodgate.listener.BungeeListener.onPostLogin(BungeeListener.java:132)
    at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:557)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)`

If you need any additional information, please feel free to reach out on Discord: xLucky#1475

**Comment by mnfu** [comment]
Seems like an issue with the commit made with Bungeecord #1641

**Comment by eleksploded** [comment]
Its due to bungee cord changing `net.md_5.bungee.connection.LoginResult$Property` to `net.md_5.bungee.protocol.Property`

**Comment by Tim203** [comment]
This has been fixed in the latest build
