### ISSUE TITLE
Bungeecord Error

### ISSUE THREAD

**Issue by WongIong** [GeyserMC/Floodgate#317]
02:27:54 [WARNING] Exception encountered when loading plugin: floodgate
java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.FloodgatePlatform.enable(org.geysermc.floodgate.shadow.com.google.inject.Module[])" because "this.platform" is null
    at org.geysermc.floodgate.BungeePlugin.onEnable(BungeePlugin.java:64)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Tim203** [comment]
This is not the full error. Please post your log here or in our Discord.

**Comment by WongIong** [comment]
Ok, after i checked the full log. Just need to delete the config.yml and it is solved now
