### ISSUE TITLE
Unlinked bedrock players are not able to skip mojang authentication

### ISSUE THREAD

**Issue by Zynaxwastaken** [GeyserMC/Floodgate#318]
I own a network that I allow bedrock players to join, I have set up geyser and floodgate on the proxy and set up floodgate on all the backend servers.  I made sure to use the same token on the backend servers as the proxy, however, bedrock players who do not have their account linked to a java account are unable to join. 

![image](https://user-images.githubusercontent.com/67625857/173232919-1996ce83-df2d-4680-a245-e84c2474ba9f.png)

This is the error I get in console:
```[13:14:58 WARN]: Exception verifying .MrNoLife420
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.18.2.jar:git-Paper-366]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.18.2.jar:git-Paper-366]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:229) ~[paper-1.18.2.jar:git-Paper-366]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:223) ~[paper-1.18.2.jar:git-Paper-366]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:401) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:282) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Zynaxwastaken** [comment]
After updating to build 68 I no longer have this issue.
