### ISSUE TITLE
Floodgate not getting disabled

### ISSUE THREAD

**Issue by TypicalShavonne** [GeyserMC/Floodgate#323]
Floodgate-spigot isnt getting disabled on server stop
When an player attempted to join, it just make some errors
`[00:22:38 INFO]: Disconnecting /1.55.194.254:44184: An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.
[00:22:38 WARN]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@38f72f28 rejected from java.util.concurrent.ThreadPoolExecutor@7b99967[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1562]
[00:22:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
[00:22:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
[00:22:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
[00:22:38 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.link.GlobalPlayerLinking.getLinkedPlayer0(GlobalPlayerLinking.java:94)
[00:22:38 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.link.GlobalPlayerLinking.getLinkedPlayer(GlobalPlayerLinking.java:81)
[00:22:38 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.player.FloodgateHandshakeHandler.fetchLinkedPlayer(FloodgateHandshakeHandler.java:254)
[00:22:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[00:22:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[00:22:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[00:22:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[00:22:38 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`
Expected: No errors

**Comment by Tim203** [comment]
Are you trying to reload your server?

**Comment by TypicalShavonne** [comment]
im not, im stopping the server

**Comment by Tim203** [comment]
Can you try the latest development version to see if this issue has been resolved?
