### ISSUE TITLE
Couldn't look up profile properties issue

### ISSUE THREAD

**Issue by sanegaming** [GeyserMC/Floodgate#329]
### Describe the bug

The server is constantly spamming the console chat with various player profiles with the following error:

[17:56:20 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6a736d2e[id=00000000-0000-0000-0009-01fd43ae45cf,name=.E1ectroxity,properties={},legacy=false]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.5.41.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:203) ~[authlib-3.5.41.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.19.jar:git-Paper-42]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:175) ~[authlib-3.5.41.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:142) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:460) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$6(SkullBlockEntity.java:139) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Unsure, this server was upgraded from 1.18 to 1.19 and has had this issue since 1.19

### Expected behaviour

I would expect if the profile is invalid to delete it, or automatically add the Name/ID as it is requesting.

### Geyser Dump

https://dump.geysermc.org/rhFyiwjFn7s16YFjKlbs97t4NKiytdMf

### Geyser Version

2.0.4-SNAPSHOT (git-master-f2f894b) 

### Minecraft: Bedrock Edition Device/Version

All devices

**Comment by ijgeoffrey** [comment]
Nice to know that this is safe to ignore, but it's definitely very annoying as a server admin because I get about 20 of them and it buries the other data in my server console.

**Comment by sanegaming** [comment]
> This has to do with looking up player heads. It's safe to ignore, and is technically a Floodgate issue.

Isn't this the floodgate github?

**Comment by Konicai** [comment]
Yes. This is the right place - its a Floodgate issue

**Comment by hedrizzle** [comment]
Still open the Issue on 1.20.2 Purpur: https://pastebin.com/XVpaxQRB

**Comment by hedrizzle** [comment]
@sanegaming @Camotoy @ijgeoffrey @Konicai 

I just found **the solution**!

i bet you guys are all on Windows Server, right?
Exlude in Windows Defender your minecraft server folder and no error in logs anymore! you're welcome xD

**Comment by Konicai** [comment]
The specific error you had isn't related to this issue

Please avoid pinging everyone in a conversation

**Comment by hedrizzle** [comment]
hm, ok, maybe not but the solution for me is still working with excluding it from windows defender. maybe someone will help this comment.
sorry for pinging everyone, it was my first post ever on github.

**Comment by MatinHQ** [comment]
Still no solution for that?

**Comment by Tim203** [comment]
Is this still a problem?

**Comment by ServerNootNoot** [comment]
Yes, this is still a problem.

**Comment by Tim203** [comment]
Which server version are you using?

**Comment by ServerNootNoot** [comment]
I'm using 1.20.4.

**Comment by TerdyTheTerd** [comment]
I see these issues on 1.21.1 Purpur with Geyser/Floodgate. Extremely annoying when the console gets hundreds of lines spammed in an instant multiple times over the course of a few minutes. Whatever "feature" is triggering these needs to have an option to disabled it.

**Comment by Tim203** [comment]
Player heads cause this. Some see this as a Floodgate issue because the Java server doesn't expect the Floodgate UUIDs, but I personally see it as improper error handling of the server.
The only thing you can disable is Floodgate itself, then the issue doesn't silently disappear though because the player heads continue to exist in your world.

**Comment by Camotoy** [comment]
On further evaluation, this might be something we can work around. Please provide a Geyser dump.

**Comment by TerdyTheTerd** [comment]
Well that's the thing, one of the UUID's is a Java UUID, it was saved somewhere in the server when I joined the backend server while it was in offline mode. It only fails with ONE of the bedrock UUID's and not both, likely because I had also joined with that bedrock account while it was in offline mode.

In any case, what is triggering these? Is it only player heads of those players?

**Comment by womzil** [comment]
It's not a minor and ignorable bug. It makes the whole server console UNUSABLE. How am I supposed to execute a command, if I can't see its output? I don't even see other errors! Any way to get rid of these errors from my server console?
