### ISSUE TITLE
java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property

### ISSUE THREAD

**Issue by YellowZaki** [GeyserMC/Floodgate#354]
This error has been around for some time. It is spammy on the console:

`[19:55:00] [Netty Worker IO Thread #15/WARN]: Error dispatching event PostLoginEvent(player=*Fadrink) to listener org.geysermc.floodgate.listener.BungeeListener@2aa28a01
java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
	at org.geysermc.floodgate.pluginmessage.BungeeSkinApplier.applySkin(BungeeSkinApplier.java:77) ~[?:?]
	at org.geysermc.floodgate.listener.BungeeListener.onPostLogin(BungeeListener.java:132) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:813) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:547372b:unknown]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]`

It seems a 1 .19 Bungeecord change.
SkinsRestorer [fixed here](https://github.com/SkinsRestorer/SkinsRestorerX/blob/693c5953612c129509aa039c9959c883c9cf48d1/bungee/src/main/java/net/skinsrestorer/bungee/SkinsRestorer.java#L88)

**Comment by Konicai** [comment]
Please update Floodgate, yours is at least 4 months old
