### ISSUE TITLE
error？

### ISSUE THREAD

**Issue by kroazi** [GeyserMC/Floodgate#356]
this is error？

[21:53:43] [connectionLostChecker-1/ERROR]: [floodgate] [debug] Got an error
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:869) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
        at org.geysermc.floodgate.skin.SkinUploadSocket.onClose(SkinUploadSocket.java:150) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-spigot.jar:?]
        at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:663) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-spigot.jar:?
]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:552) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-spigot.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:576) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-spigot.jar:?]
        at org.java_websocket.AbstractWebSocket.executeConnectionLostDetection(AbstractWebSocket.java:232) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-s
pigot.jar:?]
        at org.java_websocket.AbstractWebSocket.access$200(AbstractWebSocket.java:43) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-spigot.jar:?]
        at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:203) [%5B反 作 弊 前 置 -基 岩 版 %5Dfloodgate-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]

so what can i do？

**Comment by JonasDevDE** [comment]
Hey, try to opdate your Floodgate plugin and make sure you use the correct version for your platform.

**Comment by Chew** [comment]
It looks like you can't seem to connect to the Floodgate skin API, just based on the stack trace. Gonna close this unless someone else experiences this issue on the latest build, though. Thank you for reporting.
