### ISSUE TITLE
When I close the server this supposed error happens:

### ISSUE THREAD

**Issue by Y0hh** [GeyserMC/Floodgate#372]
```
[16:22:58] [WebSocketConnectReadThread-99/WARN]: Exception in thread "WebSocketConnectReadThread-99" java.lang.IllegalStateException: zip file closed
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at org.geysermc.floodgate.logger.JavaUtilFloodgateLogger.error(JavaUtilFloodgateLogger.java:49)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at org.geysermc.floodgate.skin.SkinUploadSocket.onError(SkinUploadSocket.java:179)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:523)
[16:22:58] [WebSocketConnectReadThread-99/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
What could this be? An error? Or is it just a plugin thing?

**Comment by Konicai** [comment]
This can be ignored, it won't affect your server. It'll be fixed when the current development branch of Floodgate is merged

**Comment by Y0hh** [comment]
Notice that this error happens when a player enters the server, well, the plugin works fine, but when I close the server it gives this warning, is there a way to solve it? But it doesn't affect anything, it just gives this error.

**Comment by Y0hh** [comment]
> This can be ignored, it won't affect your server. It'll be fixed when the current development branch of Floodgate is merged

This error somewhat bothers me, but I thank you for the answer anyway.

**Comment by Tim203** [comment]
Related PR: #363

**Comment by Tim203** [comment]
This has been fixed in the development branch.
