### ISSUE TITLE
friend cant join

### ISSUE THREAD

**Issue by NBS-Paste** [GeyserMC/Floodgate#375]
my friend cant join my server and i get an error code like this

[18:56:15 WARN]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@173ce037 rejected from java.util.concurrent.ThreadPoolExecutor@54151e5c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
[18:56:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
[18:56:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
[18:56:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
[18:56:15 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.link.GlobalPlayerLinking.getLinkedPlayer0(GlobalPlayerLinking.java:94)
[18:56:15 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.link.GlobalPlayerLinking.getLinkedPlayer(GlobalPlayerLinking.java:81)
[18:56:15 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.player.FloodgateHandshakeHandler.fetchLinkedPlayer(FloodgateHandshakeHandler.java:258)
[18:56:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[18:56:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:56:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[18:56:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[18:56:15 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[18:56:15 INFO]: Disconnecting /192.168.1.45:64913: An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.
[18:56:15 INFO]: [Geyser-Spigot] Rock Duck 84 has disconnected from remote Java server on address 192.168.1.45 because of An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.
[18:56:15 INFO]: /192.168.1.45:64913 lost connection: An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.

the weird thing is that i have other friends on bedrock that can join just fine.

**Comment by Tim203** [comment]
Most of the time this happens when you're reloading your server.
