### ISSUE TITLE
Error while implementing Floodgate's API to my plugin

### ISSUE THREAD

**Issue by TehPigYT** [GeyserMC/Floodgate#376]
Hey there,

It has been a while since I have created a plugin that uses Floodgate's API to retreive some information.
I recently reopened the project, made a change and rebuilt the jar file, but once I try it on the Minecraft Server it no longer works.

The server is currently running on Purpur 1.19.2, with the following list of plugins (no of them interfere with the plugin's functions)
```
spark, ViaVersion, ViaBackwards, ViaRewind, Verification (the plugin which I have issues with)
```

This is what I use on my `pom.xml` file
```
...
        <repository>
            <id>opencollab-snapshot</id>
            <url>https://repo.opencollab.dev/maven-snapshots/</url>
        </repository>
...
        <dependency>
            <groupId>org.geysermc.floodgate</groupId>
            <artifactId>api</artifactId>
            <version>2.2.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```

This is the error that comes up in console
```
java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at verification.verification.events.EventManager.onPlayerJoin(EventManager.java:30) ~[Verification.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1770]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:375) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:313) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1436) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 21 more
```

I have tried looking for a solution for quite some time, but none of them actually seemed to do the trick.
Any help would be really appreciated.

**Comment by Tim203** [comment]
If that's your complete plugin list then you forgot to add Floodgate as a plugin to your Purpur server.

**Comment by TehPigYT** [comment]
Adding the Floodgate plugin to the plugins folder seemed to work, thank you for you time and support!
