### ISSUE TITLE
Does Floodgate conflicts with the latest version of Velocity

### ISSUE THREAD

**Issue by herobrine666233** [GeyserMC/Floodgate#380]
The player linking implementation returned an error
java.lang.LinkageError: loader constraint violation: when resolving method 'void com.mysql.cj.ClientPreparedQuery.<init>(com.mysql.cj.NativeSession)' the class loader java.net.URLClassLoader @17fa1336 of the current class, com/mysql/cj/jdbc/ClientPreparedStatement, and the class loader com.velocitypowered.proxy.plugin.PluginClassLoader @4a9486c0 for the method's defining class, com/mysql/cj/ClientPreparedQuery, have different Class objects for the type com/mysql/cj/NativeSession used in the signature (com.mysql.cj.jdbc.ClientPreparedStatement is in unnamed module of loader java.net.URLClassLoader @17fa1336, parent loader com.velocitypowered.proxy.plugin.PluginClassLoader @6ceb7b5e; com.mysql.cj.ClientPreparedQuery is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @4a9486c0, parent loader 'app')
        at com.mysql.cj.jdbc.ClientPreparedStatement.initQuery(ClientPreparedStatement.java:157) ~[?:?]
        at com.mysql.cj.jdbc.StatementImpl.<init>(StatementImpl.java:218) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:172) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:211) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:192) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.getInstance(ClientPreparedStatement.java:133) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:670) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1643) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1563) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
        at org.geysermc.floodgate.database.MysqlDatabase.lambda$getLinkedPlayer$0(MysqlDatabase.java:108) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by herobrine666233** [comment]
@Tim203

**Comment by Tim203** [comment]
This should be fixed in the latest commit of the development branch.
