### ISSUE TITLE
floodgate 2.2 does not work on paper-1.19.3-424

### ISSUE THREAD

**Issue by neil921228** [GeyserMC/Floodgate#395]
[13:33:07 ERROR]: [floodgate] Error initializing plugin 'floodgate-spigot.jar' in folder 'plugins' (Is it up to date?)
org.geysermc.floodgate.shadow.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingMethod]: RuntimeException: Failed to load the config! Try to delete the config file if this error persists
  at FloodgatePlatform.init(FloodgatePlatform.java:84)
  while locating SpigotPlatform

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_METHOD

1 error

======================
Full classname legend:
======================
FloodgatePlatform: "org.geysermc.floodgate.FloodgatePlatform"
SpigotPlatform:    "org.geysermc.floodgate.SpigotPlatform"
========================
End of classname legend:
========================

        at org.geysermc.floodgate.shadow.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.SpigotPlugin.onLoad(SpigotPlugin.java:57) ~[floodgate-spigot.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.3.jar:git-Paper-424]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.3.jar:git-Paper-424]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[paper-1.19.3.jar:git-Paper-424]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.3.jar:git-Paper-424]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:429) ~[paper-1.19.3.jar:git-Paper-424]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-424]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-424]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-424]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to load the config! Try to delete the config file if this error persists
        at org.geysermc.floodgate.config.ConfigLoader.load(ConfigLoader.java:86) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform.init(FloodgatePlatform.java:93) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5380913.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5380913.apply(<generated>) ~[?:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[floodgate-spigot.jar:?]
        ... 11 more
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 4, column 1:
    key-file-name: key.pem
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 15, column 2:
     default-locale: zh_TW
     ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:679) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:239) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:208) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:406) ~[snakeyaml-1.33.jar:?]
        at org.geysermc.configutils.updater.ConfigUpdater.update(ConfigUpdater.java:78) ~[floodgate-spigot.jar:?]
        at org.geysermc.configutils.ConfigUtilities.update0(ConfigUtilities.java:152) ~[floodgate-spigot.jar:?]
        at org.geysermc.configutils.ConfigUtilities.createOrUpdate(ConfigUtilities.java:113) ~[floodgate-spigot.jar:?]
        at org.geysermc.configutils.ConfigUtilities.createAndMapOrUpdateAndMap(ConfigUtilities.java:86) ~[floodgate-spigot.jar:?]
        at org.geysermc.configutils.ConfigUtilities.executeOn(ConfigUtilities.java:81) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.config.ConfigLoader.load(ConfigLoader.java:84) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform.init(FloodgatePlatform.java:93) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5380913.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5380913.apply(<generated>) ~[?:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shadow.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[floodgate-spigot.jar:?]
        ... 11 more

server: paper-1.19.3-424
plugins: floodgate-spigot 2.2
              Geyser-Spigot v2.1.0
              GSit-1.3.7
              LuckPerms-Bukkit-5.4.62
             EssentialsX-2.19.7

**Comment by Tim203** [comment]
Can you send your config here? It sounds like you have done something invalid in your config

**Comment by neil921228** [comment]
@Tim203 
[config (floodgate).txt](https://github.com/GeyserMC/Floodgate/files/10838388/config.floodgate.txt)
[config (Geyser).txt](https://github.com/GeyserMC/Floodgate/files/10838400/config.Geyser.txt)

**Comment by Jens-Co** [comment]
![DCBD9701-CE17-48EA-B0C9-0FFEF9254703](https://user-images.githubusercontent.com/63231928/221537238-00253169-eb7d-43ee-9372-603423f85709.jpeg)

remove the space before default and restart the server.

**Comment by neil921228** [comment]
The server is working normally, thank you very much
