### ISSUE TITLE
Error when enabled `send-floodgate-data`

### ISSUE THREAD

**Issue by lgc2333** [GeyserMC/Floodgate#416]
<details>
<summary>Error log</summary>

```txt
[13:40:59 INFO]: [server connection] BE_student_2333 -> main has connected
[13:40:59 INFO]: [server connection] BE_student_2333 -> main has disconnected
[13:40:59 ERROR]: [connected player] BE_student_2333 (/183.94.187.14:0): unable to connect to server main
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
        at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
        at java.lang.String.substring(String.java:2707) ~[?:?]
        at org.geysermc.floodgate.addon.data.VelocityServerDataHandler.write(VelocityServerDataHandler.java:127) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:233) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.startHandshake(VelocityServerConnection.java:193) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.lambda$connect$0(VelocityServerConnection.java:117) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[13:40:59 INFO]: [connected player] BE_student_2333 (/183.94.187.14:0) has disconnected: 无法将您连接至 main，请稍后再试。
[13:40:59 INFO] [geyser]: student 2333 因为 无法将您连接至 main，请稍后再试。 与 Java 服务器断开了连接
[13:40:59 INFO] [floodgate]: Floodgate 玩家 student 2333 已断开连接
```
</details>

Geyser dump: https://dump.geysermc.org/nVY7lFxylxwqC8GimOVkT9dkVzivTCOm

<details>

<summary>Velocity dump</summary>

```json
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.2.0-SNAPSHOT (git-40b76c63-b256)"
  },
  "platform": {
    "operatingSystemType": "Windows Server 2022",
    "operatingSystemVersion": "10.0",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "17.0.6",
    "javaVendor": "Oracle Corporation",
    "listener": {
      "listenerType": "NIO",
      "compression": "Java",
      "encryption": "Java"
    }
  },
  "config": {
    "bind": "0.0.0.0:22010",
    "motd": "打我服务器没妈妈",
    "showMaxPlayers": 500,
    "onlineMode": false,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "NONE",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "ALL",
    "advanced": {
      "compressionThreshold": 256,
      "compressionLevel": -1,
      "loginRatelimit": 3000,
      "connectionTimeout": 5000,
      "readTimeout": 30000,
      "proxyProtocol": false,
      "tcpFastOpen": false,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": true,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": true,
      "queryPort": 22010,
      "queryMap": "Velocity",
      "showPlugins": true
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": true,
    "servers": {
      "main": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 25565
      }
    },
    "connectOrder": [
      "main"
    ],
    "forcedHosts": {}
  },
  "plugins": [
    {
      "id": "allmusic",
      "name": "AllMusic",
      "version": "2.18.8",
      "authors": [
        "Color_yr"
      ],
      "description": "全服点歌插件",
      "url": "https://github.com/Coloryr/AllMusic_P"
    },
    {
      "id": "floodgate",
      "name": "floodgate",
      "version": "2.2.2-SNAPSHOT (b56-e23f1b2)",
      "authors": [
        "GeyserMC"
      ],
      "description": "Allows Bedrock players to join Java edition servers while keeping the server in online mode",
      "url": "https://geysermc.org}"
    },
    {
      "id": "geyser",
      "name": "Geyser-Velocity",
      "version": "2.1.0-SNAPSHOT (git-master-246ebdd)",
      "authors": [
        "GeyserMC"
      ],
      "url": "https://geysermc.org"
    },
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.12",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.12",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    },
    {
      "id": "limbofilter",
      "name": "LimboFilter",
      "version": "1.1.10",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi"
      ]
    }
  ]
}
```

</details>

<details>

<summary>Server `main`'s Mod list</summary>

```txt
- aqupdhat 1.19.4-2.5.0
   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
        \-- packet_tweaker 0.3.1+23w06a
- architectury 8.1.79
- badpackets 0.4.1
- carpet 1.4.101+v230319
- carpet-extra 1.4.100
- carpet-tis-addition 1.46.1
   \-- conditional-mixin 0.3.2
- chathistory 1.5.0+1.19.3
- chatimage 1.1.4+1.19.3+fabric
   |-- com_madgag_animated-gif-lib 1.4
   |-- com_squareup_okhttp3_okhttp 4.10.0
   \-- net_sf_image4j_image4j 0.7.2
- chunky 1.3.74
- cloth-config 10.0.96
   \-- cloth-basic-math 0.6.1
- cmdspy 1.3.2
- debugify 1.19.4+1.0
   \-- com_github_llamalad7_mixinextras 0.1.1
- diggusmaximus 1.5.8-1.19.4
   \-- kyrptconfig 1.5.2-1.19.4
- dynview 1.19-3.2
- essential_commands 0.32.0-mc1.19.4
   |-- ec-core 1.3.0-mc1.19.4
   |    |-- fabric-permissions-api-v0 0.2-SNAPSHOT
   |    |-- placeholder-api 2.0.0-pre.2+1.19.3
   |    \-- playerabilitylib 1.7.0
   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
   |-- placeholder-api 2.0.0-pre.2+1.19.3
   \-- playerabilitylib 1.7.0
- fabric-api 0.76.0+1.19.4
   |-- fabric-api-base 0.4.23+9ff28bcef4
   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
   |-- fabric-command-api-v1 1.2.25+f71b366ff4
   |-- fabric-command-api-v2 2.2.4+ae0966baf4
   |-- fabric-commands-v0 0.2.42+df3654b3f4
   |-- fabric-containers-v0 0.1.52+df3654b3f4
   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
   |-- fabric-item-api-v1 2.1.16+09a3510cf4
   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
   |-- fabric-loot-api-v2 1.1.25+75e98211f4
   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
   |-- fabric-models-v0 0.3.29+11ba9c3bf4
   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
   |-- fabric-networking-v0 0.3.39+df3654b3f4
   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
   |-- fabric-particles-v1 1.0.22+f1e4495bf4
   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
   |-- fabric-rendering-v0 1.1.40+df3654b3f4
   |-- fabric-rendering-v1 2.1.0+8f878217f4
   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
   |-- fabric-sound-api-v1 1.0.8+75e98211f4
   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
- fabric-language-kotlin 1.9.3+kotlin.1.8.20
   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.20
   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.20
   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.20
   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.20
   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.1
   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
- fabricloader 0.14.19
- fabrictailor 2.0.2
   \-- config2brigadier 1.2.1
- ferritecore 5.2.0
- floodgate 2.2.0-SNAPSHOT
- gca 2.6.0-1.19.4
- htm 1.1.8
   \-- common-protection-api 1.0.0
- image2map 0.4.1
   |-- map-canvas-api 0.2.2+1.19.4
   \-- sgui 1.2.1+1.19.3
- invview 1.4.10-1.19.3+
   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
- itemflexer 1.3.0
   \-- microconfig 2.2.1
- java 17
- journeymap 5.9.5
   \-- journeymap-api-fabric 1.19.4-1.9-fabric-SNAPSHOT
- ledger 1.2.7
   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
- lithium 0.11.1
- luckperms 5.4.71
   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
- magiclib 0.7.318+85c565a-beta
   \-- magiclib-1_19_4 0.7.318+85c565a-beta
- minecraft 1.19.4
- minecraft-command-permissions 1.6.1
- mods-command 1.1.2
   |-- adventure-platform-fabric 5.8.0
   |    |-- net_kyori_adventure-api 4.13.0
   |    |-- net_kyori_adventure-key 4.13.0
   |    |-- net_kyori_adventure-platform-api 4.2.0
   |    |-- net_kyori_adventure-text-logger-slf4j 4.13.0
   |    |-- net_kyori_adventure-text-minimessage 4.13.0
   |    |-- net_kyori_adventure-text-serializer-gson 4.13.0
   |    |-- net_kyori_adventure-text-serializer-plain 4.13.0
   |    |-- net_kyori_examination-api 1.3.0
   |    \-- net_kyori_examination-string 1.3.0
   |-- cloud 1.8.3
   |    |-- cloud_commandframework_cloud-brigadier_ 1.8.3
   |    |-- cloud_commandframework_cloud-core_ 1.8.3
   |    |-- cloud_commandframework_cloud-services_ 1.8.3
   |    \-- fabric-permissions-api-v0 0.2-SNAPSHOT
   |-- cloud_commandframework_cloud-minecraft-extras 1.8.3
   |-- com_typesafe_config 1.4.2
   |-- io_leangen_geantyref_geantyref 1.3.13
   |-- org_spongepowered_configurate-core 4.1.2
   |-- org_spongepowered_configurate-hocon 4.1.2
   \-- org_spongepowered_configurate-yaml 4.1.2
- pca 0.3.157+daa8ade-beta
   \-- pca-1_19_4 0.3.157+daa8ade-beta
- quickshulker 1.3.10-1.19.4
   |-- kyrptconfig 1.5.2-1.19.4
   \-- shulkerutils 1.0.4-1.19
- roughlyenoughitems 11.0.597
   \-- error_notifier 1.0.9
- servux 0.1.0
- spark 1.10.34
- starlight 1.1.1+fabric.ae22326
- syncmatica 1.18.2-0.3.8
- trampledisablerfabric 1.0.7
- viabackwards 4.6.1
- viafabric 0.4.10+33-dev
   |-- cotton-client-commands 1.1.0+1.15.2
   |-- org_yaml_snakeyaml 2.0
   |-- viafabric-mc119 0.4.10+33-dev
   \-- viaversion 4.7.0-23w14a-SNAPSHOT
- worldedit 7.2.14+6360-094b734
```

</details>

**Comment by Tim203** [comment]
Which forwarding mode are you using?

**Comment by lgc2333** [comment]
> Which forwarding mode are you using?

player info forward mode? it is `none`

**Comment by lgc2333** [comment]
because of limbo api does not work with other forwarding modes (maybe)

**Comment by Konicai** [comment]
Floodgate can't send *data* if you've disabled *data sending*.

**Comment by Tim203** [comment]
Support for Velocity's none forwarding has been added in the development branch.
It'll probably take quite a bit before you could start using it.

However, I expect that limbo api does support other forwarding modes. So for now please contact them to see what your options are.

**Comment by lgc2333** [comment]
ok, i will

**Comment by lgc2333** [comment]
alright, it's my configuration problem
how fool am i :clown_face:
