### ISSUE TITLE
Folia Unsupported

### ISSUE THREAD

**Issue by JekoTC** [GeyserMC/Floodgate#425]
[04:12:27] [Server thread/INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b88-2278589)
[04:12:27] [Server thread/ERROR]: Error occurred while enabling floodgate v2.2.2-SNAPSHOT (b88-2278589) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[floodgate-spigotfoloia.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:631) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:542) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.ServerConnection
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:112) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:103) ~[floodgate-spigotfoloia.jar:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.ServerConnection
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:110) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[floodgate-spigotfoloia.jar:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:103) ~[floodgate-spigotfoloia.jar:?]
	... 16 more
[04:12:27] [Server thread/INFO]: [floodgate] Disabling floodgate v2.2.2-SNAPSHOT (b88-2278589)

**Comment by toinouH** [comment]
Hello,
Would you fill the issue template correctly ?
Could you link us where you did download floodgate-spigotfolia ?

**Comment by JekoTC** [comment]
the originame is floogate-spigot.jar

**Comment by Konicai** [comment]
You're using the mojang mapped (mojmap) folia jar instead of the normal one.
