### ISSUE TITLE
Could not load plugin from file plugins\floodgate.jar because 'java.util.zip.ZipException: zip END header not found'

### ISSUE THREAD

**Issue by wifi-left** [GeyserMC/Floodgate#429]
Version: 2.2.2 build 59
(https://download.geysermc.org/v2/projects/floodgate/versions/2.2.2/builds/59/downloads/bungee)

Logs:
```
[13:56:43 WARN]: Could not load plugin from file plugins\floodgate.jar
java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:428) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
```

**Comment by Konicai** [comment]
Wasn't able to reproduce. This is typically caused by an unfinished or corrupt download.
