### ISSUE TITLE
UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.

### ISSUE THREAD

**Issue by XXY233** [GeyserMC/Floodgate#432]
There is an UnexpectedEncryptionException when certain players connect from Geyser.
I've only found this to be the case for two players so far, their Xbox Gamertag is H4LFSOUL3078 and F4DEZERO, the others can connect fine.

Geyser Dump: https://dump.geysermc.org/EOxKMFKG6aTpfNoIzNHzfs90mTJ4LaOk

```
[13:55:12] [epollEventLoopGroup-5-1/INFO] [geyser]: /122.231.146.53:11771 Trying to connect!
[13:55:13] [epollEventLoopGroup-5-1/INFO] [geyser]: Player connected as username H4LFSOUL3078
[13:55:13] [defaultEventLoopGroup-7-7/INFO] [geyser]: H4LFSOUL3078 (login as: H4LFSOUL3078) connected to Java server
[13:55:18] [pool-8-thread-7/INFO] [floodgate]: Floodgate player who is logged in as H4LFSOUL3079 3c33397b-2490-43dc-ba7f-23aa373ecc6f joined
[13:55:18] [Velocity Async Event Executor - #2/INFO] [fastlogin]: Incoming login request for H4LFSOUL3078 from /122.231.146.53:0
[13:55:18] [FastLoginVelocity - Task Executor #303/INFO] [fastlogin]: Handling player H4LFSOUL3078
[13:55:18] [FastLoginVelocity - Task Executor #303/INFO] [fastlogin]: Requesting premium login for registered player: H4LFSOUL3078
[13:55:18] [defaultEventLoopGroup-7-7/INFO] [geyser]: H4LFSOUL3078 because of trying to log in as a Java Edition player! Is Floodgate set up correctly? Disconnected from Java Edition server
[13:55:18] [Netty epoll Worker #6/INFO] [floodgate]: Floodgate player H4LFSOUL3078 disconnected
[13:55:18] [Netty epoll Worker #6/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [initial connection] /122.231.146.53:0 has disconnected
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: com.github.steveice10.mc.protocol.data.UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:56)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:157)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:388)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:29)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[13:55:18] [defaultEventLoopGroup-7-7/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Tim203** [comment]
Please try it again without FastLogin. We don't offer support for those plugins.

**Comment by XXY233** [comment]
Floodgate works fine without FastLogin. Well, it should be a FastLogin problem.
