### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by schiwi2779** [GeyserMC/Floodgate#433]
[WebSocketConnectReadThread-277/WARN]: Exception in thread "WebSocketConnectReadThread-277" java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.EntityScheduler org.bukkit.entity.Player.getScheduler()'
[19:49:34] [WebSocketConnectReadThread-277/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.util.SpigotVersionSpecificMethods.hideAndShowPlayer(SpigotVersionSpecificMethods.java:67)
[19:49:34] [WebSocketConnectReadThread-277/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.lambda$applySkin0$1(SpigotSkinApplier.java:97)
[19:49:34] [WebSocketConnectReadThread-277/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.util.SpigotVersionSpecificMethods.maybeSchedule(SpigotVersionSpecificMethods.java:98)
[19:49:34] [WebSocketConnectReadThread-277/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:94)
![IMG_20230803_202256](https://github.com/GeyserMC/Floodgate/assets/128501666/dc63784b-881a-47d2-a158-1252cfbf5a47)

I'm using paper 1.20 and geyser/floodgate latest version

**Comment by Tim203** [comment]
This should be fixed in the latest commit.
