### ISSUE TITLE
NPE on stopping PlayerLink during shutdown

### ISSUE THREAD

**Issue by vodkodav** [GeyserMC/Floodgate#441]
Using OpenJRE 19 and the latest versions of papermc, geyser and Floodgate. no other plugins.
When I stop the server, an error appears in the logs:

java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.api.link.PlayerLink.stop()" because "this.instance" is null
        at org.geysermc.floodgate.link.PlayerLinkHolder.onShutdown(PlayerLinkHolder.java:222) ~[floodgate-spigot.jar:?]
        at org.lanternpowered.lmbda.Lmbda$3.accept(Unknown Source) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fireSilently(EventBusImpl.java:37) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fire(EventBusImpl.java:37) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform.disable(FloodgatePlatform.java:82) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.SpigotPlugin.onDisable(SpigotPlugin.java:94) ~[floodgate-spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-129]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.1.jar:git-Paper-129]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.1.jar:git-Paper-129]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:571) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:806) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-129]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by Tim203** [comment]
Can you upload your server logs to https://mclo.gs

**Comment by Tim203** [comment]
This should be fixed in build 69

**Comment by vodkodav** [comment]
How fast, thanks!

> Can you upload your server log to https://mclo.gs ?

It doesn't seem necessary anymore, but still...
https://mclo.gs/avyJxn7
