### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by rogerxavier93** [GeyserMC/Floodgate#452]
[12:17:44] [Server thread/INFO]: [floodgate] Loading server plugin floodgate v2.2.2-SNAPSHOT (b139-66cf8a3)
[12:17:45] [Server thread/WARN]: [floodgate] Missing locale file: en_US
[12:17:45] [Server thread/ERROR]: [floodgate] Failed to load the fallback language. This will likely cause errors!
[12:17:45] [Server thread/WARN]: [floodgate] en_US is not a supported Floodgate language.
[12:17:45] [Server thread/ERROR]: [floodgate] Error initializing plugin 'floodgate-spigot.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "properties" is null
	at org.geysermc.floodgate.util.LanguageManager.getString(LanguageManager.java:158) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.util.LanguageManager.getLogString(LanguageManager.java:136) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.logger.JavaUtilFloodgateLogger.translatedInfo(JavaUtilFloodgateLogger.java:76) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.SpigotPlugin.onLoad(SpigotPlugin.java:62) ~[floodgate-spigot.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-201]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by rogerxavier93** [comment]
Using https://github.com/GeyserMC/Floodgate/pull/449

**Comment by rogerxavier93** [comment]
tried erasing floodgate folder to see if it fixes it but still same error using paper 1.20.2

**Comment by rogerxavier93** [comment]
@Kas-tle im using the build artifacts from the pr

**Comment by rogerxavier93** [comment]
the spigot one

**Comment by Kas-tle** [comment]
Then I'm not sure what's wrong. I tested with the experimental paper builds and had no issues.

**Comment by Kas-tle** [comment]
Actually I think I see the issue. Could you try with the artifact from the repo build action (so my 1.20.2 branch) instead of the PR action?

**Comment by Kas-tle** [comment]
No. The issue was that the PR build action was not setup to clone the module that contains the language files before building. The latest build should fix this. Thanks for bringing this to my attention.
