### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Floodgate#459]
Exception in thread "WebSocketConnectReadThread-5826" java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.currentSkin(SpigotSkinApplier.java:105)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:81)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:54)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at floodgate-spigot.jar//org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
[20:38:16] [WebSocketConnectReadThread-5826/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

Version: 2.2.2-SNAPSHOT (b??-104cbdd)

**Comment by onebeastchris** [comment]
Did you update Floodgate?
This should be fixed with https://github.com/GeyserMC/Floodgate/commit/71acc6c0f4884952cce1269efc174caec7f635b0
