### ISSUE TITLE
Error after pinging server

### ISSUE THREAD

**Issue by ChefMC** [GeyserMC/Floodgate#461]
### Describe the bug

```
[21:19:53 ERROR]: java.lang.reflect.InvocationTargetException
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:53 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:53 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[21:19:53 ERROR]:       at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:53 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:53 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[21:19:53 ERROR]:       at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[21:19:53 ERROR]:       at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[21:19:53 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[21:19:53 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[21:19:53 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:19:53 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:19:53 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:19:53 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:19:53 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:19:53 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[21:19:53 ERROR]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[21:19:53 ERROR]:       at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[21:19:53 ERROR]:       ... 30 more
[21:19:53 ERROR]: java.lang.reflect.InvocationTargetException
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:53 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:53 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[21:19:53 ERROR]:       at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:53 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:53 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:53 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[21:19:53 ERROR]:       at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[21:19:53 ERROR]:       at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[21:19:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[21:19:53 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[21:19:53 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[21:19:53 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[21:19:53 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:19:53 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:19:53 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:19:53 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:19:53 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:19:53 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[21:19:53 ERROR]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[21:19:53 ERROR]:       at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[21:19:53 ERROR]:       ... 30 more
[21:19:56 ERROR]: java.lang.reflect.InvocationTargetException
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:56 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:56 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[21:19:56 ERROR]:       at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:56 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:56 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[21:19:56 ERROR]:       at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[21:19:56 ERROR]:       at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[21:19:56 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[21:19:56 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[21:19:56 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:19:56 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:19:56 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:19:56 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:19:56 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:19:56 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[21:19:56 ERROR]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[21:19:56 ERROR]:       at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[21:19:56 ERROR]:       ... 30 more
[21:19:56 ERROR]: java.lang.reflect.InvocationTargetException
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:56 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:56 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[21:19:56 ERROR]:       at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:19:56 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:56 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:19:56 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[21:19:56 ERROR]:       at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[21:19:56 ERROR]:       at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[21:19:56 ERROR]:       at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[21:19:56 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[21:19:56 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[21:19:56 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[21:19:56 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:19:56 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:19:56 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:19:56 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:19:56 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:19:56 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[21:19:56 ERROR]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[21:19:56 ERROR]:       at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[21:19:56 ERROR]:       ... 30 more
```

### To Reproduce

1. Add server into Minecraft multiplayer list
2. Refresh

### Expected behaviour

No any console errors should be

### Server Version and Plugins

Velocity:
![image](https://github.com/GeyserMC/Geyser/assets/3519015/c132b797-027d-4a8a-878e-5b4faa2002da)

### Geyser Dump

https://dump.geysermc.org/qqxfXlggvvsJ8sDZYBarUUBoggHrDllR

### Geyser Version

Geyser-Velocity build 340

**Comment by onebeastchris** [comment]
Transferred to Floodgate as it appears to be a conflict between floodgate-velocity and protocolize
