### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'

### ISSUE THREAD

**Issue by DexterSK** [GeyserMC/Floodgate#464]
`[15:25:05 WARN]: Exception in thread "WebSocketConnectReadThread-5714" java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
[15:25:05 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.currentSkin(SpigotSkinApplier.java:105)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:81)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:54)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
[15:25:05 WARN]:        at floodgate-spigot.jar//org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
[15:25:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)`

git-Purpur-2083 (MC: 1.20.2)*

**Comment by onebeastchris** [comment]
Fixed in this commit - https://github.com/GeyserMC/Floodgate/commit/71acc6c0f4884952cce1269efc174caec7f635b0.
Please update Floodgate
