### ISSUE TITLE
1.12.2 server running ViaVersion cant be joined by Java Edition clients on 1.15.2.

### ISSUE THREAD

**Issue by satyrnhub** [GeyserMC/Floodgate#47]
I am running a server with Mohist 1.12.2. The server is running ViaVersion to provide support for 1.15.2 aswell. Although I'm not sure this is the problem, I might as well add it. 

Floodgate fails to allow Java clients to join or see the MOTD, spitting this error out: `> [21:31:49 WARN]: Failed to initialize a channel. Closing: [id: 0x1adb1a2f, L:/172.18.0.4:25610 - R:/73.140.237.254:51650]
java.lang.ExceptionInInitializerError: null
at org.geysermc.floodgate.injector.BukkitInjector$2$1.initChannel(BukkitInjector.java:72) ~[?:?]
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:220) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[PluginClassLoader.class:1.12.2-8077ffd]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[PluginClassLoader.class:1.12.2-8077ffd]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
at red.mohist.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:24) ~[ProxyClass.class:1.12.2-8077ffd]
at red.mohist.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:20) ~[ProxyClass.class:1.12.2-8077ffd]
at org.geysermc.floodgate.util.ReflectionUtil.getClass(ReflectionUtil.java:23) ~[?:?]
at org.geysermc.floodgate.util.ReflectionUtil.getPrefixedClass(ReflectionUtil.java:18) ~[?:?]
at org.geysermc.floodgate.PacketHandler.<clinit>(PacketHandler.java:169) ~[?:?]
... 11 more
> [21:31:49 WARN]: Failed to initialize a channel. Closing: [id: 0x98ed2661, L:/172.18.0.4:25610 - R:/73.140.237.254:51656]
java.lang.NoClassDefFoundError: Could not initialize class org.geysermc.floodgate.PacketHandler
at org.geysermc.floodgate.injector.BukkitInjector$2$1.initChannel(BukkitInjector.java:72) ~[?:?]
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [21:31:49 WARN]: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: null
at net.minecraft.network.NetworkManager.closeChannel(NetworkManager.java:313) ~[gw.class:?]
at net.minecraft.network.NetworkManager.channelInactive(NetworkManager.java:132) ~[gw.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [minecraft_server.1.12.2.jar:?]
at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [minecraft_server.1.12.2.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

Any help?

**Comment by DoctorMacc** [comment]
Next time, please follow the issue template.

You're saying that Java Edition clients are unable to connect? Can you confirm that this is different without Floodgate?

**Comment by RednedEpic** [comment]
Modded servers are not supported. Additionally, this looks quite similar to an error you’d get when trying to run Floodgate on CraftBukkit. Problem is likely due to the fact that since Forge is in the mix, MCP mappings are being used vs Spigot ones, so in that case Floodgate won’t work at all.

**Comment by DoctorMacc** [comment]
(Also, my apologies, there is no issue template on Floodgate)

**Comment by satyrnhub** [comment]
Thanks for the information.
