### ISSUE TITLE
Errors on player join (Folia 1.20.2)

### ISSUE THREAD

**Issue by roggy666** [GeyserMC/Floodgate#470]
![IMG_20231129_114643](https://github.com/GeyserMC/Floodgate/assets/59109355/43a2e773-e602-4bdb-9811-681eac90aea2)
[10:49:39] [Region Scheduler Thread #2/INFO]: [floodgate] Floodgate player logged in as Vano5769 joined (UUID: 00000000-0000-0000-0009-01f697e3bc4b)
[10:49:39] [Netty Epoll Server IO #1/WARN]: [ProtocolLib] Failed to process inbound packet event: PacketEvent[player=CraftPlayer{name=Vano5769}, packet=PacketContainer[type=null[class=ServerboundClientInformationPacket, id=0], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@371c0c13]]]]
java.lang.NullPointerException: null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.1.2-jre.jar:?]
    at com.google.common.cache.LocalCache.put(LocalCache.java:4242) ~[guava-32.1.2-jre.jar:?]
    at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.cachePlayerKey(ConcurrentPlayerMap.java:195) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:206) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:27) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:148) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:131)

**Comment by roggy666** [comment]
(This problem is only when a bedrock player connects, the lib protocol gets null from the floodgate as I understand it

**Comment by Tim203** [comment]
Do you have an issue link somewhere (e.g. from ProtocolLib)?

**Comment by Tim203** [comment]
Closing due do inactivity
