### ISSUE TITLE
Tried to login as a java edition player, is floodgate set up correctly 

### ISSUE THREAD

**Issue by badawy1135** [GeyserMC/Floodgate#474]
i dont know what i did wrong i just installed the geyser plugin and floodgate with nothing else and it doesnt work

**Comment by badawy1135** [comment]
<html>
<body>

[18:34:00] [Server thread/ERROR]: Error occurred while enabling floodgate v2.2.2-SNAPSHOT (b85-71acc6c) (Is it up to date?)
--
222 | java.lang.ExceptionInInitializerError: null
223 | at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[?:?]
224 | at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[?:?]
225 | at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[?:?]
226 | at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[?:?]
227 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
228 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
229 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
230 | at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
231 | at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
232 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
233 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
234 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
235 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
236 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
237 | at java.lang.Thread.run(Thread.java:840) ~[?:?]
238 | Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R3.LoginListener$LoginHandler
239 | at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:112) ~[?:?]
240 | at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
241 | at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:186) ~[?:?]
242 | ... 15 more
243 | Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R3.LoginListener$LoginHandler
244 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
245 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
246 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
247 | at java.lang.Class.forName0(Native Method) ~[?:?]
248 | at java.lang.Class.forName(Class.java:375) ~[?:?]
249 | at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:110) ~[?:?]
250 | at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
251 | at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:186) ~[?:?]
252 | ... 15 more


</body>
</html>[18:34:00] [Server thread/ERROR]: Error occurred while enabling floodgate v2.2.2-SNAPSHOT (b85-71acc6c) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[?:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:[250](https://aternos.org/log/#L250)) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4001-Spigot-49e36b8-1da8d9a]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R3.LoginListener$LoginHandler
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:112) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:186) ~[?:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R3.LoginListener$LoginHandler
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:110) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:186) ~[?:?]
	... 15 more

**Comment by badawy1135** [comment]
this is the error message

**Comment by Tim203** [comment]
For now the solution is to either downgrade to a Spigot version older than yesterday or move to Paper.
However we're actively looking into this issue.

**Comment by badawy1135** [comment]
> For now the solution is to either downgrade to a Spigot version older than yesterday or move to Paper. However we're actively looking into this issue.

thanks bro i will do that and you can close it if you feel thats enough or just continue trying to fix it for older generations

**Comment by Tim203** [comment]
The latest Floodgate build (87) should fix this issue
