### ISSUE TITLE
Unable to provision with NoSuchMethodError: 'void CustomClassLoaderConstructor.<init>(ClassLoader)' on Purpur 1.20.4

### ISSUE THREAD

**Issue by Muska-Ami** [GeyserMC/Floodgate#488]
Use: floodgate-spigot
```
> version
[13:37:51 INFO]: Checking version, please wait...
[13:37:52 INFO]: Current: git-Purpur-2152 (MC: 1.20.4)*
Previous: git-Purpur-2136 (MC: 1.20.4)
* You are running the latest version
```
```
[13:32:41 INFO]: [floodgate] Loading server plugin floodgate v2.1.0-SNAPSHOT
[13:32:42 ERROR]: [floodgate] Error initializing plugin 'floodgate-spigot.jar' in folder 'plugins' (Is it up to date?)
org.geysermc.floodgate.shaded.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingMethod]: NoSuchMethodError: 'void CustomClassLoaderConstructor.<init>(ClassLoader)'
  at FloodgatePlatform.init(FloodgatePlatform.java:88)
  while locating SpigotPlatform

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_METHOD

1 error

======================
Full classname legend:
======================
CustomClassLoaderConstructor: "org.yaml.snakeyaml.constructor.CustomClassLoaderConstructor"
FloodgatePlatform:            "org.geysermc.floodgate.FloodgatePlatform"
SpigotPlatform:               "org.geysermc.floodgate.SpigotPlatform"
========================
End of classname legend:
========================

        at org.geysermc.floodgate.shaded.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.SpigotPlugin.onLoad(SpigotPlugin.java:57) ~[floodgate-spigot.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2152]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.constructor.CustomClassLoaderConstructor.<init>(java.lang.ClassLoader)'
        at org.geysermc.floodgate.config.loader.ConfigInitializer.<clinit>(ConfigInitializer.java:47) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.config.loader.ConfigLoader.load(ConfigLoader.java:78) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform.init(FloodgatePlatform.java:97) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5340096.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at org.geysermc.floodgate.FloodgatePlatform$$FastClassByGuice$$5340096.apply(<generated>) ~[?:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.shaded.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[floodgate-spigot.jar:?]
        ... 11 more
```

**Comment by Muska-Ami** [comment]
well, fixed
