### ISSUE TITLE
crashing upon server startup

### ISSUE THREAD

**Issue by IXSENPA1XI** [GeyserMC/Floodgate#490]
video : https://drive.google.com/file/d/1v8ag_auBRZwEsn4Vmqdoxkua1oBZxINl/view?usp=drivesdk
2024-03-19 17:44:36,176 main ERROR Unable to delete file D:\MINECRAFT SERVER\logs\latest.log: java.nio.file.FileSystemException D:\MINECRAFT SERVER\logs\latest.log: The process cannot access the file because it is being used by another process
2024-03-19 17:44:36,203 main ERROR Unable to delete file D:\MINECRAFT SERVER\logs\debug.log: java.nio.file.FileSystemException D:\MINECRAFT SERVER\logs\debug.log: The process cannot access the file because it is being used by another process
[17:44:36.313] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 20.4.196, --fml.fmlVersion, 2.0.17, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 20231207.154220]
[17:44:36.317] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.2 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[17:44:36.509] [main/INFO] [loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[17:44:36.614] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/MINECRAFT%20SERVER/libraries/net/fabricmc/sponge-mixin/0.13.0+mixin.0.8.5/sponge-mixin-0.13.0+mixin.0.8.5.jar%2379!/ Service=ModLauncher Env=SERVER
[17:44:36.737] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Geyser-NeoForge.jar" of type MOD with provider {mods folder locator at D:\MINECRAFT SERVER\mods}
[17:44:36.839] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "server-1.20.4-20231207.154220-srg.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@2ca65ce4
[17:44:36.840] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-20.4.196-universal.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@2ca65ce4
[17:44:36.955] [main/INFO] [loading.moddiscovery.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[17:44:36.956] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "mixinextras-neoforge-0.3.5.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@82c57b3
[17:44:38.980] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17:44:39.002] [main/INFO] [LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
2024-03-19 17:44:39,483 main WARN Advanced terminal features are not available in this environment
[17:44:39] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[17:44:45] [modloading-worker-0/INFO] [ne.ne.ne.co.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 20.4.196, for MC 1.20.4 with MCP 20231207.154220
[17:44:46] [modloading-worker-0/INFO] [geyser/]: Loading extensions...
[17:44:46] [modloading-worker-0/INFO] [geyser/]: Loaded 0 extension(s)
[17:44:46] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[17:44:46] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?] {}
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:75) ~[?:?] {}
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137) ~[?:?] {}
        at sun.nio.ch.IOUtil.write(IOUtil.java:81) ~[?:?] {}
        at sun.nio.ch.IOUtil.write(IOUtil.java:72) ~[?:?] {}
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:300) ~[?:?] {}
        at net.minecraft.util.DirectoryLock.create(DirectoryLock.java:37) ~[server-1.20.4-20231207.154220-srg.jar%23126!/:?] {re:classloading}
        at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.<init>(LevelStorageSource.java:441) ~[server-1.20.4-20231207.154220-srg.jar%23126!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.storage.LevelStorageSource.validateAndCreateAccess(LevelStorageSource.java:374) ~[server-1.20.4-20231207.154220-srg.jar%23126!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:138) ~[server-1.20.4-20231207.154220-srg.jar%23126!/:?] {re:classloading}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by onebeastchris** [comment]
Please upload a proper log file via mclo.gs instead of sharing a video file.

**Comment by IXSENPA1XI** [comment]
https://drive.google.com/file/d/1mlX8yUAWwxkjLPMofFwO8UdYHZm-ScYs/view?usp=drivesdk

**Comment by IXSENPA1XI** [comment]
[Uploading 2024-03-19-1.log.gz…]()

**Comment by IXSENPA1XI** [comment]
[debug.log](https://github.com/GeyserMC/Floodgate/files/14657309/debug.log)

**Comment by IXSENPA1XI** [comment]
[debug-1.log.gz](https://github.com/GeyserMC/Floodgate/files/14657311/debug-1.log.gz)

**Comment by IXSENPA1XI** [comment]
[latest.log](https://github.com/GeyserMC/Floodgate/files/14657312/latest.log)

**Comment by onebeastchris** [comment]
You've shared a neoforge server log, which is neither related to floodgate nor geyser.

 `java.io.IOException: The process cannot access the file because another process has locked a portion of the file`
 That just states that your server cannot start as it's already running - since something else is locking the file.

**Comment by IXSENPA1XI** [comment]
> Please upload a proper log file via mclo.gs instead of sharing a video file.

there are all the log files as well as video and a copy paste from the cmd terminal
hopfully this all helps

**Comment by IXSENPA1XI** [comment]
it was malware bytes  you can close this ticket and mark as solved

**Comment by IXSENPA1XI** [comment]
fixed first issue ran into another one

**Comment by IXSENPA1XI** [comment]
https://github.com/GeyserMC/Floodgate/issues/491

**Comment by IXSENPA1XI** [comment]
> You've shared a neoforge server log, which is neither related to floodgate nor geyser.
> 
> `java.io.IOException: The process cannot access the file because another process has locked a portion of the file` That just states that your server cannot start as it's already running - since something else is locking the file.

https://github.com/GeyserMC/Floodgate/issues/491 ran into another problem

**Comment by onebeastchris** [comment]
As I've mentioned in that issue, you should ask in the NeoForge discord for help with NeoForge. This is not a Floodgate issue - heck, Floodgate-neoforge does not even exist.

**Comment by IXSENPA1XI** [comment]
ight
