### ISSUE TITLE
Error occurred while enabling floodgate v2.2.3-SNAPSHOT (b99-7a55305) (Is it up to date?)

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Floodgate#500]
Error occurred while enabling floodgate v2.2.3-SNAPSHOT (b99-7a55305) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[?:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net/minecraft/server/v1_8_R3//MinecraftServer
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:112) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:124) ~[?:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_8_R3//MinecraftServer
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:110) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:124) ~[?:?]
	... 15 more

Error occurred while enabling floodgate v2.2.3-SNAPSHOT (b99-7a55305) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[?:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:398) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:295) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:630) ~[patched_1.12.2.jar:git-Dionysus-"8d3095e"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net/minecraft/server/v1_12_R1//MinecraftServer
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:112) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:124) ~[?:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_12_R1//MinecraftServer
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:110) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:124) ~[?:?]
	... 15 more

**Comment by adalmo** [comment]
i am getting this issue on 1.8.8 and 1.12.2 server

**Comment by Tim203** [comment]
This should be fixed in the build that was just released
