### ISSUE TITLE
UnknownHostException leads to players timing out

### ISSUE THREAD

**Issue by mikaschulz01** [GeyserMC/Floodgate#517]
## Overview
Hi guys, I got an UnknownHostException on api.geyermc.org today. 

### Lobby-Server Log
```bash
[11:29:50] [WebSocketConnectReadThread-11496/ERROR]: [floodgate] Got an error
java.net.UnknownHostException: api.geysermc.org
	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:948) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1638) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1504) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1393) ~[?:?]
	at org.java_websocket.client.WebSocketClient$1.resolve(WebSocketClient.java:224) ~[floodgate-spigot.jar:?]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:472) ~[floodgate-spigot.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
### Geyer-Standalone Log
```bash
[11:29:25.383 WebSocketConnectReadThread-1405/ERROR] Unable to resolve the skin api! This can be caused by your connection or the skin api being unreachable. api.geysermc.org: Temporary failure in name resolution
```
## Consequences
Apparently there was a DNS timeout here. As a result, all players were kicked off the server.
### Plot-Server Log
```bash
[11:28:51] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:51] [Server thread/INFO]: xxxxxxxxx lost connection: Disconnected
[11:28:52] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:52] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:55] [Server thread/INFO]: xxxxxxxxx lost connection: Disconnected
[11:28:56] [Server thread/WARN]: xxxxxxxxx was kicked due to keepalive timeout!
[11:28:56] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:56] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:57] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:57] [Server thread/WARN]: xxxxxxxxx was kicked due to keepalive timeout!
[11:28:57] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
[11:28:59] [Server thread/INFO]: xxxxxxxxx lost connection: Timed out
```
It seems to me that something is blocking, unless the resolution of the dns names was sucessful.
is this a desired behavior?

Btw.: Times are in CEST

**Comment by Tim203** [comment]
The skin stuff runs separately from the individual connections, so I think that you were disconnected from the internet for a bit which lead to the timeouts and Floodgate not being able to resolve the skin api
