### ISSUE TITLE
Floodgate doesn't load under Spigot 1.21

### ISSUE THREAD

**Issue by Fanman03** [GeyserMC/Floodgate#520]
Floodgate build 107 doesn't load under Spigot 1.21 and gives the following error message.

```[16:52:03] [Server thread/INFO]: [floodgate] Enabling floodgate v2.2.3-SNAPSHOT (b107-c4a4487)
[16:52:04] [Server thread/INFO]: [floodgate] Disabling floodgate v2.2.3-SNAPSHOT (b107-c4a4487)
[16:52:04] [Server thread/ERROR]: Error occurred (in the plugin loader) while enabling floodgate v2.2.3-SNAPSHOT (b107-c4a4487) (Is it up to date?)
org.apache.logging.log4j.core.appender.AppenderLoggingException: An exception occurred processing Appender ServerGuiConsole
    at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:95) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.AppenderControl.handleAppenderError(AppenderControl.java:169) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:162) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:575) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.Logger.log(Logger.java:169) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2933) ~[log4j-api-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886) ~[log4j-api-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868) ~[log4j-api-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2647) ~[log4j-api-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2594) ~[log4j-api-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:835) ~[log4j-api-2.22.1.jar:2.22.1]
    at org.bukkit.craftbukkit.v1_21_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:32) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at java.logging/java.util.logging.Logger.log(Logger.java:983) ~[?:?]
    at java.logging/java.util.logging.Logger.doLog(Logger.java:1010) ~[?:?]
    at java.logging/java.util.logging.Logger.log(Logger.java:1121) ~[?:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4196-Spigot-146439e-a4c2ee7]
    at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
    at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
    at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
    at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
    at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:172) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:117) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
    at org.geysermc.floodgate.shadow.com.google.inject.internal.InternalErrorDetail.getErrorIdentifier(InternalErrorDetail.java:58) ~[?:?]
    at org.geysermc.floodgate.shadow.com.google.inject.spi.ErrorDetail.format(ErrorDetail.java:62) ~[?:?]
    at org.geysermc.floodgate.shadow.com.google.inject.internal.Messages.formatMessages(Messages.java:90) ~[?:?]
    at org.geysermc.floodgate.shadow.com.google.inject.CreationException.getMessage(CreationException.java:50) ~[?:?]
    at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:108) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:96) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:353) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.layout.PatternLayout$NoFormatPatternSerializer.toSerializable(PatternLayout.java:355) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.layout.PatternLayout$NoFormatPatternSerializer.toSerializable(PatternLayout.java:346) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:229) ~[log4j-core-2.22.1.jar:2.22.1]
    at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:58) ~[log4j-core-2.22.1.jar:2.22.1]
    at com.mojang.logging.plugins.QueueLogAppender.append(QueueLogAppender.java:34) ~[logging-1.2.7.jar:?]
    at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160) ~[log4j-core-2.22.1.jar:2.22.1]
```

This also prevents Bedrock clients from connecting to the server (using Geyser build 557). Clients receive the error message: 

![image](https://github.com/GeyserMC/Floodgate/assets/6323431/3261f0ca-fde8-49ae-b936-c5753d8cb194)

**Comment by Camotoy** [comment]
We are aware of this issue. We will resolve it when we figure out what's going on.
