### ISSUE TITLE
Tried to connect as a Java Edition player! Is Floodgate configured correctly?

### ISSUE THREAD

**Issue by Jim-m-y** [GeyserMC/Floodgate#530]
Well, I will quickly explain what is happening, and forgive me if my English is bad, I don't know much English. "Tried to connect as a Java Edition player! Is Floodgate configured correctly?" It appears on some very rare occasions, it happens to me and almost everyone who plays on my server, I'm not running anything behind a proxy but in the end it does let you connect to the server, but sometimes it just appears to a user and doesn't let them connect to the server and you have to try a few times to let them log in.

**Comment by Guillaume351** [comment]
Same issue for me, using PaperMC + Geyser (spigot plugin) + Floodgate (spigot plugin)

**Comment by More678** [comment]
Same issue for me, using PaperMC(1.18.2) + Geyser (spigot newest) + Floodgate (spigot newest)

**Comment by Kamology** [comment]
Just got this too, I'm on less than week old versions of everything but technically not latest so I'll update and report back if it persists.

**Comment by Tim203** [comment]
Is this still an issue? If so please try to make it reproducible e.g. with just Paper + Geyser + Floodgate.
Write down which version of Paper & the plugins you are using, and if any config changes were made to either one of them.
If more plugins than those are needed, also include just the problematic plugins and their versions.
This would help me find the issue and fixing it.

**Comment by Yashvardhan76** [comment]
Hey The reason of this issue is because  when user has already joined the java server with username **(i.e. coolboy)** and a bedrock player try to rejoin it with **(.coolboy)** then it throw this error the **solution is to change the bedrock account** for now. I face this issue when I testing on my server which have same java username as bedrock gamertag.

**Comment by Tim203** [comment]
I'm not sure how that could be causing the issue, since the UUID should still be properly set if the username is.
Or do you suggest that Floodgate reports the correct username, but the server isn't?

There does seem to be a rare issue where Floodgate would fail to even getting notified about a player joining, which will result in the player being rejected in online-mode servers. And players having the incorrect uuid & username in offline mode.
This does seem to match the description of this issue.
However, we've not yet found the root cause for this issue.

**Comment by Angrite** [comment]
Same problem with Purpur 1.21.4-2416-HEAD@51aafbc +  Geyser-Spigot (2.7.1-SNAPSHOT) + floodgate (2.2.4-SNAPSHOT (b116-0e3163c).  I face this issue with different Java and Bedrock account names. 

Server logs:

[11:51:45 INFO]: [Geyser-Spigot] Player connected with username XXXXXXXXX
[11:51:45 INFO]: [Geyser-Spigot] XXXXXXXXX (logged in as: XXXXXXXXX) has connected to the Java server
[11:51:45 INFO]: [Geyser-Spigot] XXXXXXXXX has disconnected from the Java server because of Tried to log in as a Java Edition player! Is Floodgate set up correctly?

**Comment by Angrite** [comment]
Extended server log with geyser option debug-mode=true:

[00:08:57] [epollEventLoopGroup-14-3/INFO]: [Geyser-Spigot] Is player data signed? true
[00:08:57] [epollEventLoopGroup-14-3/INFO]: [Geyser-Spigot] Could not find packet for ClientToServerHandshakePacket
[00:08:57] [epollEventLoopGroup-14-3/INFO]: [Geyser-Spigot] Could not find packet for ClientCacheStatusPacket
[00:08:57] [epollEventLoopGroup-14-3/INFO]: [Geyser-Spigot] Player connected with username XXXXXXXXXXXXX
[00:08:57] [localSession-7-4/INFO]: [Geyser-Spigot] XXXXXXXXXXXXX (logged in as: XXXXXXXXXXXXX) has connected to the Java server
[00:08:57] [localSession-7-4/INFO]: [Geyser-Spigot] Locale already loaded: en_us
[00:08:57] [localSession-7-4/INFO]: [Geyser-Spigot] XXXXXXXXXXXXX has disconnected from the Java server because of Tried to log in as a Java Edition player! Is Floodgate set up correctly?
[00:08:57] [localSession-7-4/WARN]: [Geyser-Spigot] Cannot reply to ClientboundHelloPacket without profile and access token.
[00:08:57] [Server thread/INFO]: XXXXXXXXXXXXX (/AAA.BBB.CCC.DDD:0) lost connection: Disconnected
[00:08:58] [localSession-7-4/WARN]: org.geysermc.mcprotocollib.protocol.data.UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.
[00:08:58] [localSession-7-4/WARN]: 	at Geyser-Spigot.jar//org.geysermc.mcprotocollib.protocol.ClientListener.packetReceived(ClientListener.java:72)
[00:08:58] [localSession-7-4/WARN]: 	at Geyser-Spigot.jar//org.geysermc.mcprotocollib.network.session.NetworkSession.callPacketReceived(NetworkSession.java:144)
[00:08:58] [localSession-7-4/WARN]: 	at Geyser-Spigot.jar//org.geysermc.mcprotocollib.network.session.NetworkSession.channelRead0(NetworkSession.java:321)
[00:08:58] [localSession-7-4/WARN]: 	at Geyser-Spigot.jar//org.geysermc.mcprotocollib.network.session.NetworkSession.channelRead0(NetworkSession.java:39)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:323)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:469)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:427)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:08:58] [localSession-7-4/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[00:08:58] [localSession-7-4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
