### ISSUE TITLE
Errors on 1.21

### ISSUE THREAD

**Issue by Teslicek** [GeyserMC/Floodgate#534]
Plugin Version: Floodgate b109
Minecraft Server Version: UniverseSpigot 1.21
```
[08:06:50 ERROR]: [org.java_websocket.drafts.Draft_6455] Runtime exception during onWebsocketMessage
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinDataImpl.<init>(SkinDataImpl.java:45) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.util.SpigotVersionSpecificMethods.currentSkin(SpigotVersionSpecificMethods.java:97) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:80) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:53) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) ~[Floodgate #109.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[08:06:50 ERROR]: [floodgate] Got an error
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinDataImpl.<init>(SkinDataImpl.java:45) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.util.SpigotVersionSpecificMethods.currentSkin(SpigotVersionSpecificMethods.java:97) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:80) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:53) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) ~[Floodgate #109.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by Tim203** [comment]
I expect that this is an issue with the fork you're using, since I'd expect more people to report issues if Paper/Spigot changed anything. Please report this to the developer(s) of UniverseSpigot. We only ensure compatibility with Spigot and Paper.

**Comment by Teslicek** [comment]
> I expect that this is an issue with the fork you're using, since I'd expect more people to report issues if Paper/Spigot changed anything. Please report this to the developer(s) of UniverseSpigot. We only ensure compatibility with Spigot, Paper and Folia.

This has nothing to do with our server software. I can assure you that it is a fork of paper and is not causing any issues.
The issue started occuring when we created a plugin that is saving player heads, it works, but floodgate is spamming errors/exceptions every now and then.

**Comment by Tim203** [comment]
Is it maybe possible that you are using a proxy and you forgot to update Floodgate there?

**Comment by Teslicek** [comment]
> Is it maybe possible that you are using a proxy and you forgot to update Floodgate there?

No. We have floodgate b109 both on proxy & on backend. The errors/exceptions happen when a bedrock player joins.
```
[15:12:12 INFO]: _CrazyEv28[IP hidden] logged in with entity id 380334 at ([world]64.5, 69.0, 0.5)
[15:12:12 INFO]: [+] _CrazyEv28 (Geyser)
[15:12:12 ERROR]: [org.java_websocket.drafts.Draft_6455] Runtime exception during onWebsocketMessage
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinDataImpl.<init>(SkinDataImpl.java:45) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.util.SpigotVersionSpecificMethods.currentSkin(SpigotVersionSpecificMethods.java:97) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:80) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:53) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) ~[Floodgate #109.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:12:12 ERROR]: [floodgate] Got an error
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinDataImpl.<init>(SkinDataImpl.java:45) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.util.SpigotVersionSpecificMethods.currentSkin(SpigotVersionSpecificMethods.java:97) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:80) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:53) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) ~[Floodgate #109.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by Tim203** [comment]
Then I expect that your heads plugin is doing something funky. Floodgate looks if there is an existing skin on the player, but the skin that is on the player does not have a signature. Player heads don't require a signature, but player skins do.

**Comment by Teslicek** [comment]
> Then I expect that your heads plugin is doing something funky. Floodgate looks if there is an existing skin on the player, but the skin that is on the player does not have a signature. Player heads don't require a signature, but player skins do.

```
public static String fetchHeadTexture(UUID uuid) {
        String texture = playerTextureCache.get(uuid);

        if (texture != null) {
            return texture;
        }

        if (isBedrockPlayer(uuid)) {
            return fetchBedrockSkin(uuid);
        } else {
            return fetchJavaSkin(uuid);
        }
    }

    private static boolean isBedrockPlayer(UUID uuid) {
        return uuid.toString().startsWith("00000000-");
    }

    private static String fetchJavaSkin(UUID uuid) {
        String profileUrl = "https://sessionserver.mojang.com/session/minecraft/profile/" + uuid.toString().replace("-", "");
        try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
            HttpGet request = new HttpGet(profileUrl);
            try (CloseableHttpResponse response = httpClient.execute(request)) {
                if (response.getStatusLine().getStatusCode() == 200) {
                    String jsonResponse = EntityUtils.toString(response.getEntity());
                    JsonObject profile = JsonParser.parseString(jsonResponse).getAsJsonObject();
                    JsonArray properties = profile.getAsJsonArray("properties");

                    if (!properties.isEmpty()) {
                        JsonObject firstProperty = properties.get(0).getAsJsonObject();
                        String texture = firstProperty.get("value").getAsString();

                        if (texture != null && !texture.isEmpty()) {
                            playerTextureCache.put(uuid, texture);
                            return texture;
                        }
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    private static String fetchBedrockSkin(UUID uuid) {
        String xuid = convertToXUID(uuid);
        String profileUrl = "https://api.geysermc.org/v2/skin/" + xuid;
        try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
            HttpGet request = new HttpGet(profileUrl);
            try (CloseableHttpResponse response = httpClient.execute(request)) {
                if (response.getStatusLine().getStatusCode() == 200) {
                    String jsonResponse = EntityUtils.toString(response.getEntity());
                    JsonObject profile = JsonParser.parseString(jsonResponse).getAsJsonObject();

                    // Check if "value" exists and is not null
                    if (profile.has("value") && !profile.get("value").isJsonNull()) {
                        String textureValue = profile.get("value").getAsString();

                        if (textureValue != null && !textureValue.isEmpty()) {
                            playerTextureCache.put(uuid, textureValue);
                            return textureValue;
                        }
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    private static String convertToXUID(UUID uuid) {
        String uuidStr = uuid.toString().replace("-", "");
        String partWithoutZeroes = uuidStr.substring(16); // Get the last 12 characters
        long xuid = Long.parseLong(partWithoutZeroes, 16);
        return String.valueOf(xuid);
    }
```
