### ISSUE TITLE
geyser

### ISSUE THREAD

**Issue by hotbonnix** [GeyserMC/Floodgate#539]
```
[11:21:44] [epollEventLoopGroup-4-4/INFO]: [Geyser-Spigot] Player connected with username Pooka8236
[11:[2](https://mclo.gs/kvKazR8#L2)1:44] [localSession-7-4/INFO]: [Geyser-Spigot] Pooka8236 (logged in as: Pooka8236) has connected to the Java server
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: java.lang.NullPointerException
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:2[3](https://mclo.gs/kvKazR8#L3)3)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at java.base/java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:5[4](https://mclo.gs/kvKazR8#L4)7)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:[5](https://mclo.gs/kvKazR8#L5)7)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:444)
[11:21:44] [Geyser Spigot connection thread-[6](https://mclo.gs/kvKazR8#L6)-1/WARN]: 	at floodgate-spigot (1).jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:150)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at floodgate-spigot (1).jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:145)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at floodgate-spigot (1).jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:1[7](https://mclo.gs/kvKazR8#L7)8)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:31[8](https://mclo.gs/kvKazR8#L8))
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:[9](https://mclo.gs/kvKazR8#L9)97)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[11:21:44] [Geyser Spigot connection thread-6-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[[11](https://mclo.gs/kvKazR8#L11):21:44] [localSession-7-4/INFO]: [Geyser-Spigot] Pooka8236 has disconnected from the Java server because of End of stream
[11:21:44] [Server thread/INFO]: /**.**.**.**:0 lost connection: Disconnected
```

https://mclo.gs/tGENWcQ

**Comment by Tim203** [comment]
I'm not entirely sure how this is possible. It seems like the handshake packet is missing, and instead it starts directly with the login start packet.
Does this error happen often and are other people experiencing this issue as well?
And I can't help noticing a login plugin being in your plugin list. Please remove the login plugin and try again.
