### ISSUE TITLE
Latest version of BungeeCord gives an error

### ISSUE THREAD

**Issue by Mrnobody1539** [GeyserMC/Floodgate#544]
Plugin dont load 

18:27:34 [WARNING] Exception encountered when loading plugin: floodgate
java.lang.RuntimeException: Failed to inject the packet listener!
at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:73)
at org.geysermc.floodgate.BungeePlugin.onEnable(BungeePlugin.java:64)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.AccessibleObject.isAccessible()" because "accessibleObject" is null
at org.geysermc.floodgate.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:570)
at org.geysermc.floodgate.util.ReflectionUtils.getValue(ReflectionUtils.java:249)
at org.geysermc.floodgate.util.ReflectionUtils.getCastedValue(ReflectionUtils.java:300)
at org.geysermc.floodgate.util.ReflectionUtils.castedStaticValue(ReflectionUtils.java:319)
at org.geysermc.floodgate.inject.bungee.BungeeInjector.inject(BungeeInjector.java:72)
at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71)
... 5 more

**Comment by Tim203** [comment]
This is caused by SpigotMC/Bungeecord#3737, for now the workaround would be to use the last build before that specific commit.
That would be https://ci.md-5.net/job/BungeeCord/1867/

**Comment by andrewkm** [comment]
Thank you for looking into this guys! :)

**Comment by Tim203** [comment]
The latest build of Floodgate fixes this issue.
The downloads can, as always, be found on https://geysermc.org/download?project=floodgate
