### ISSUE TITLE
Where should I place floodgate-sqlite-database.jar in fabric server?

### ISSUE THREAD

**Issue by win1010525** [GeyserMC/Floodgate#545]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'floodgate'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
Caused by: org.geysermc.floodgate.shadow.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: NoClassDefFoundError: org/geysermc/floodgate/link/CommonPlayerLink
  at CommonModule.playerLink(CommonModule.java:137)
  at FloodgatePlatform.init(FloodgatePlatform.java:60)
      \_ for 2nd parameter link
  while locating FloodgatePlatform

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
CommonModule:         "org.geysermc.floodgate.core.module.CommonModule"
FloodgatePlatform:    "org.geysermc.floodgate.core.FloodgatePlatform"
========================
End of classname legend:
========================

	at org.geysermc.floodgate.shadow.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.mod.FloodgateMod.init(FloodgateMod.java:25) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.platform.fabric.FabricFloodgateMod.onInitialize(FabricFloodgateMod.java:26) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: org/geysermc/floodgate/link/CommonPlayerLink
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1023) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.geysermc.floodgate.core.link.PlayerLinkHolder.load0(PlayerLinkHolder.java:176) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.core.link.PlayerLinkHolder.load(PlayerLinkHolder.java:78) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.core.module.CommonModule.playerLink(CommonModule.java:137) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.core.module.CommonModule$$FastClassByGuice$$13a7e4.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at org.geysermc.floodgate.core.module.CommonModule$$FastClassByGuice$$13a7e4.apply(<generated>) ~[?:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.mod.FloodgateMod.init(FloodgateMod.java:25) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.platform.fabric.FabricFloodgateMod.onInitialize(FabricFloodgateMod.java:26) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.link.CommonPlayerLink
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1023) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.geysermc.floodgate.core.link.PlayerLinkHolder.load0(PlayerLinkHolder.java:176) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.core.link.PlayerLinkHolder.load(PlayerLinkHolder.java:78) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.core.module.CommonModule.playerLink(CommonModule.java:137) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.core.module.CommonModule$$FastClassByGuice$$13a7e4.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at org.geysermc.floodgate.core.module.CommonModule$$FastClassByGuice$$13a7e4.apply(<generated>) ~[?:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.shadow.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.mod.FloodgateMod.init(FloodgateMod.java:25) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at org.geysermc.floodgate.platform.fabric.FabricFloodgateMod.onInitialize(FabricFloodgateMod.java:26) ~[fabric-Floodgate-Fabric-2.2.4-b33.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
	... 6 more

**Comment by onebeastchris** [comment]
Already being tracked in https://github.com/GeyserMC/Floodgate-Modded/issues/134 - working on a fix
