### ISSUE TITLE
Error occurred while enabling floodgate

### ISSUE THREAD

**Issue by abc13131412** [GeyserMC/Floodgate#560]
I’m using floodgate with Arclight and got this error when starting up.
Game Version 1.20.4

```
[12:51:11 INFO] [floodgate]: Enabling floodgate v2.2.3-SNAPSHOT (b114-83fbd6e)
[12:51:11 ERROR] [Minecraft]: Error occurred while enabling floodgate v2.2.3-SNAPSHOT (b114-83fbd6e) (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.FloodgatePlatform.enable(org.geysermc.floodgate.shadow.com.google.inject.Module[])" because "this.platform" is null
        at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServerMixin.java:541) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServerMixin.java:455) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zdk000$arclight$enablePlugins(MinecraftServerMixin.java:2197) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServerMixin.java:411) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServerMixin.java:330) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(DedicatedServerMixin_Vanilla.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:2075) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Tim203** [comment]
This part of the exception doesn't actually show the issue, but hybrids aren't supported by Floodgate.
You could however try the neoforge/fabric variants of Floodgate
