### ISSUE TITLE
Player linking implementation returned an error

### ISSUE THREAD

**Issue by andrewkm** [GeyserMC/Floodgate#565]
Have been getting this quite a lot lately;
Paper 1.21.4 Build 15.
Floodgate build against: https://github.com/GeyserMC/Floodgate/commit/06f2ed966ed82ea20b70757137d84a904ce177a8

```
[06:20:28] [pool-63-thread-9/ERROR]: [floodgate] The player linking implementation returned an error
java.lang.RuntimeException: Failed to read response
	at floodgate-spigot.jar/org.geysermc.floodgate.util.HttpClient.readDefaultResponse(HttpClient.java:143) ~[floodgate-spigot.jar:?]
	at floodgate-spigot.jar/org.geysermc.floodgate.util.HttpClient.get(HttpClient.java:65) ~[floodgate-spigot.jar:?]
	at floodgate-spigot.jar/org.geysermc.floodgate.link.GlobalPlayerLinking.lambda$getLinkedPlayer0$1(GlobalPlayerLinking.java:101) ~[floodgate-spigot.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive; at path $
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1152) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1361) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1262) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1199) ~[gson-2.11.0.jar:?]
	at floodgate-spigot.jar/org.geysermc.floodgate.util.HttpClient.readDefaultResponse(HttpClient.java:140) ~[floodgate-spigot.jar:?]
	... 6 more
```

If you need more information let me know.

**Comment by Tim203** [comment]
I think this was a temporary issue while our API was having issues, let me know if this issue still persists.
The error message can be improved though

**Comment by andrewkm** [comment]
> I think this was a temporary issue while our API was having issues, let me know if this issue still persists.
> 
> The error message can be improved though

I have not seen it since I believe.
