### ISSUE TITLE
NoSuchMethodError Enabling Floodgate on Velocity

### ISSUE THREAD

**Issue by ishland** [GeyserMC/Floodgate#59]
Stacktrace: 
```
java.lang.NoSuchMethodError: com.velocitypowered.api.command.CommandManager.register(Ljava/lang/String;Lcom/velocitypowered/api/command/Command;[Ljava/lang/String;)V
        at org.geysermc.floodgate.VelocityPlugin.onProxyInitialization(VelocityPlugin.java:96) ~[?:?]
        at net.kyori.event.asm.generated.fe6d95e326.VelocityPlugin-onProxyInitialization-ProxyInitializeEvent-4.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.0.10-SNAPSHOT (git-b26c9026-bunknown)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.0.10-SNAPSHOT (git-b26c9026-bunknown)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[velocity.jar:1.0.10-SNAPSHOT (git-b26c9026-bunknown)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[velocity.jar:1.0.10-SNAPSHOT (git-b26c9026-bunknown)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by DoctorMacc** [comment]
Which Velocity version are you using?

**Comment by ishland** [comment]
`Velocity 1.0.10-SNAPSHOT (git-b26c9026-bunknown)`
And when I login using BE it kicks me with "Connection closed"

**Comment by DoctorMacc** [comment]
We only support Velocirty 1.1.0 which is likely your issue: https://ci.velocitypowered.com/job/velocity-1.1.0/

**Comment by ishland** [comment]
Will try that later

**Comment by ishland** [comment]
I am getting errors from viaver using 1.1.0

**Comment by Tim203** [comment]
So that problem has been fixed by updating to 1.1.0 and you only get a ViaVersion error now?

**Comment by ishland** [comment]
Yep and i cannot join some of my server due to Outdated Server

**Comment by Tim203** [comment]
Then you have to add ViaVersion

**Comment by Tim203** [comment]
If you're still having issues, please join the Discord. But this doesn't look like a valid Floodgate problem.
