### ISSUE TITLE
java.lang.NullPointerException onDisable onEnable onPreLogin

### ISSUE THREAD

**Issue by LukaPix** [GeyserMC/Floodgate#70]
```
java.lang.NullPointerException: null
at org.geysermc.floodgate.BungeePlugin.lambda$onPreLogin$0(BungeePlugin.java:87) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[avalanche.jar:git-Avalanche-29]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_181]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

Is being sent to my console every now and then.

`Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@70f02c32, id=74, owner=org.geysermc.floodgate.BungeePlugin@e1e2e5e, task=org.geysermc.floodgate.BungeePlugin$$Lambda$668/1195010648@1f93c4ad, delay=0, period=0, running=true) encountered an exception`

Also this is thrown, everytime the server closes or opens

```
java.lang.NullPointerException: null
at org.geysermc.floodgate.BungeePlugin.onDisable(BungeePlugin.java:62) ~[?:?]
at net.md_5.bungee.BungeeCord.independentThreadStop(BungeeCord.java:473) ~[avalanche.jar:git-Avalanche-29]
at net.md_5.bungee.BungeeCord.access$000(BungeeCord.java:100) ~[avalanche.jar:git-Avalanche-29]
at net.md_5.bungee.BungeeCord$5.run(BungeeCord.java:413) ~[avalanche.jar:git-Avalanche-29]
```

This happens everytime ANY Player tries to log in, Java aswell as Bedrock and they get timed out.

Everything works fine with only Geyser, this only happens as i added Floodgate.

Setup: Waterfall 1.16 Bungee with Geyser and Floodgate. Geyser setup to use Floodgate.
Also have LuckPerms, Protocolize, AutoReconnect and BungeeGuard on the Waterfall
OS: Win10
Java: 8_JDK_181

**Comment by DoctorMacc** [comment]
BungeeGuard may be the one interfering.

**Comment by Tim203** [comment]
Any update on this?

**Comment by Tim203** [comment]
I'm going to close this issue since this issue has been open since late September.
